// Pure money math for the Plan (no I/O).
export {
	AFFORDABILITY_LIMITS,
	type AnythingCheck,
	type AnythingInput,
	anythingCheck,
	type CarCheck,
	type CarInput,
	type CarOption,
	type CarWay,
	carCheck,
	dollars,
	estimateGrossIncome,
	type HomeCheck,
	type HomeInput,
	homeCheck,
	loanBalance,
	monthlyPayment,
	monthsToSave,
	type PlanNow,
	type Reason,
	TAKE_HOME_SHARE,
	typicalFreeToSpend,
	type Verdict,
	type Verdicted,
} from "./affordability";
export { parseCapturedAmount } from "./capture";
export {
	AUTO_FILE_CONFIDENCE,
	type Categorization,
	type CategorizationMethod,
	decideCategorization,
	merchantKey,
	type Rule,
	ruleFor,
	SIMILAR_MERCHANT_SCORE,
} from "./categorize";
export {
	comingUp,
	type Due,
	type DueStatus,
	duesBetween,
	type Lump,
	lumpsIn,
	lumpyMonths,
	type MatchedCharge,
	matchCharges,
} from "./coming-up";
export {
	byNextDue,
	CADENCES,
	type Cadence,
	type CommitmentTerms,
	dueDatesIn,
	expectedIn,
	monthlyEquivalent,
	nextDueDate,
	yearlyCost,
} from "./commitments";
export { type CoverSource, coverSources, leftToMove } from "./cover";
export {
	describeLever,
	type LeverDescription,
	type LeverSubjects,
	leverName,
	shortMonthName,
} from "./describe-levers";
export {
	type AttributedSpend,
	type For,
	type ForTotals,
	forTotals,
	noForTotals,
	type SpendTotal,
	shares,
} from "./for";
export {
	ACCOUNT_KINDS,
	type AccountKind,
	type AccountWithdrawal,
	accountBalance,
	attributeWithdrawal,
	type BalanceUpdate,
	type EarmarkChange,
	earmarkOf,
	type GoalProgress,
	type GoalStatus,
	goalProgress,
	holdsMoney,
	splitAccount,
	type WithdrawalAttribution,
} from "./goals";
export {
	activeLevers,
	addedTerms,
	addedUntil,
	changedTerms,
	dueDateFrom,
	holdsIn,
	type Lever,
	type LeverKind,
	type LeverMute,
	type LeverOf,
	type LeverRange,
	type LeverV1,
	type OneOffFlow,
	rangeFrom,
	readScenarioLevers,
	SCENARIO_VERSION,
	type ScenarioJson,
	upgradeLevers,
	whyNotApplicable,
} from "./levers";
export { type BucketUse, likelyBucketOrder } from "./likely";
export {
	autoMatches,
	clearPairs,
	MATCH_WINDOW,
	type MatchSide,
	merchantSimilarity,
	possibleMatches,
	withinMatchWindow,
} from "./matching";
export { type Cents, MAX_CENTS, parseDollars } from "./money";
export {
	addDays,
	addMonths,
	type DayKey,
	dayKeyAt,
	daysBetween,
	daysInMonth,
	lastDayOf,
	type MonthKey,
	monthKeyAt,
	monthOfDay,
	monthsBetween,
} from "./month";
export {
	defaultDecision,
	fitsProposal,
	type Leftover,
	type MonthCloseDecision,
	type MonthCloseProposal,
	monthCloseProposal,
	nothingToClose,
} from "./month-close";
export {
	type BucketState,
	type BucketStatus,
	type Charge,
	type CommitmentState,
	type CommitmentStatus,
	type GoalFunding,
	type MonthState,
	type Move,
	monthState,
	type Spend,
	type Sweep,
} from "./month-state";
export {
	bucketsPassingPace,
	defaultNudgePreferences,
	isQuietAt,
	minuteOfDayAt,
	type NudgeKind,
	type NudgePreferences,
	nextLocalMinute,
	nudgeDeliveryTime,
	PACE_NUDGE_MIN_DAYS_LEFT,
	type QuietHours,
	wantsNudge,
} from "./nudges";
export { readOfxStatement } from "./ofx";
export {
	leverHoldsIn,
	type MonthBreakdown,
	monthBreakdown,
	type OutcomeWarning,
	outcomeWarnings,
	projectionAssumptions,
} from "./outcomes";
export {
	type BucketRecord,
	type CommitmentRecord,
	canAssign,
	commitmentsIn,
	freeToSpend,
	type Plan,
	type PlanBucket,
	type PlanCommitment,
	type PlanRecords,
	planForMonth,
	totalAllowances,
	totalCommitments,
} from "./plan";
export {
	PLAN_CHANGE_KINDS,
	type PlanChange,
	type PlanChangeGroup,
	type PlanChangeKind,
	type PlanChangeSource,
	type PlanChangeValue,
	whatChanged,
} from "./plan-history";
export { type PlanChanges, type PlanScope, planChanges, restoreAfterJust } from "./plan-scope";
export {
	type AmountBand,
	addMonthsToDay,
	COMPARISONS,
	type Comparison,
	cashFlow,
	changeOf,
	comparisonRange,
	csvDollars,
	type DayRange,
	defaultGrouping,
	earmarkHistory,
	type Flow,
	type ForCell,
	freeToSpendOver,
	GROUPINGS,
	type Grouping,
	headlines,
	incomeByMonth,
	levelOf,
	mergeCells,
	monthsIn,
	overThreshold,
	periodKey,
	periodKeys,
	periodRange,
	periodStart,
	planHabits,
	planVsActual,
	projectedCompletion,
	REPORT_PERIODS,
	type ReportPeriod,
	recurringSplit,
	regroupMonthly,
	type SpendCell,
	seriesOf,
	spendFor,
	sumOf,
	type Target,
	THRESHOLD_STOPS,
	targetId,
	targetKind,
	toCsv,
	topWithOther,
	totalsBy,
	type Variance,
} from "./reports";
export { type MonthlySpend, rolledOver, rolloverSince } from "./rollover";
export {
	type LeverImpact,
	leverImpacts,
	MAX_PROJECTION_MONTHS,
	moneyFreed,
	type PlanAhead,
	type ProjectedGoal,
	type ProjectedMonth,
	type Projection,
	type ProjectionGoal,
	type ProjectOptions,
	planAhead,
	project,
} from "./scenario";
export {
	type AssignedTransaction,
	type Assignment,
	assignedParts,
	type GoalSpend,
	type Split,
	type SplitAssignment,
	splitRemainder,
	splitsBalance,
} from "./splits";
export { readStatement } from "./statement-file";
export {
	type ClosingBalance,
	type CsvMapping,
	DATE_FORMATS,
	type DateFormat,
	guessCsvMapping,
	guessDateFormat,
	normalizeDescription,
	parseCsv,
	parseStatementAmount,
	parseStatementDate,
	readCsvStatement,
	type Statement,
	type StatementFormat,
	type StatementLine,
	statementFormat,
	statementLineIds,
} from "./statements";
export {
	likelyOriginals,
	REFUND_WINDOW_DAYS,
	type RefundSide,
	TRANSFER_WINDOW_DAYS,
	type TransferSide,
	transferPairs,
} from "./transfers";
export {
	INCOME_WARNING_FROM_DAY,
	type Income,
	type IncomeCheck,
	incomeCheck,
	receivedIn,
	type WindfallDestination,
	type WindfallSuggestion,
	windfallOf,
	windfallSuggestions,
} from "./windfall";
