// Pure money math for the Plan (no I/O).
export {
	AFFORDABILITY_LIMITS,
	type AnythingCheck,
	type AnythingInput,
	anythingCheck,
	type CarCheck,
	type CarInput,
	type CarOption,
	type CarWay,
	carCheck,
	dollars,
	estimateGrossIncome,
	type HomeCheck,
	type HomeInput,
	homeCheck,
	loanBalance,
	monthlyPayment,
	monthsToSave,
	type PlanNow,
	type Reason,
	TAKE_HOME_SHARE,
	typicalFreeToSpend,
	type Verdict,
	type Verdicted,
} from "./affordability";
export { type ApplyPreview, type ApplyPreviewInput, applyPreview } from "./apply-preview";
export {
	ACCOUNT_NAME_MAX,
	accountLabel,
	accountMask,
	type BankAccount,
	type BankLine,
	bankAccountName,
	dollarsToCents,
	type PlaidAccount,
	type PlaidTransaction,
	plaidAccountKind,
	plaidBankAccount,
	plaidLine,
} from "./bank-connections";
export {
	type BankRow,
	type BankRowChange,
	type BankSyncPlan,
	bankLineKey,
	planBankSync,
	resplit,
} from "./bank-sync";
export {
	BELL_LIMIT,
	type Bell,
	type BellRelease,
	type BellRow,
	type BellSeen,
	bell,
	NUDGES_NOT_RECORDED,
	nudgeIsRecorded,
	type RecordedNudge,
	releaseUrl,
	startingBellSeen,
} from "./bell";
export { looksPersonToPerson, parentNamedIn } from "./between-us";
export {
	type BucketGroup,
	cleanGroupName,
	GROUP_NAME_MAX,
	groupBuckets,
	groupNames,
	groupTotals,
	inGroupOrder,
	peersOf,
	putInOrder,
} from "./bucket-groups";
export { parseCapturedAmount } from "./capture";
export * from "./card-issuers";
export { paidToCards } from "./card-paid";
export {
	AUTO_FILE_CONFIDENCE,
	type Categorization,
	type CategorizationMethod,
	decideCategorization,
	type GuessMethod,
	merchantKey,
	type Rule,
	ruleFor,
	SIMILAR_GUESS_SCORE,
	SIMILAR_MERCHANT_SCORE,
} from "./categorize";
export {
	changePreset,
	parseChangePreset,
} from "./change-presets";
export {
	activeChanges,
	addedTerms,
	addedUntil,
	changedTerms,
	dueDateFrom,
	holdsIn,
	isAssumption,
	type OneOffFlow,
	oneOffAsGoal,
	rangeFrom,
	readScenarioChanges,
	SCENARIO_VERSION,
	type ScenarioChange,
	type ScenarioChangeKind,
	type ScenarioChangeMute,
	type ScenarioChangeOf,
	type ScenarioChangeRange,
	type ScenarioChangeV1,
	type ScenarioJson,
	upgradeChanges,
	whyNotApplicable,
} from "./changes";
export {
	CHECK_IN_MINUTE,
	CHECK_IN_ORDER,
	type CheckInCard,
	type CheckInCardKind,
	type CheckInDoer,
	type CheckInStackCard,
	type CheckInStarted,
	type CheckInStep,
	type CheckInWaiting,
	checkInCards,
	checkInCount,
	checkInDealtBefore,
	checkInNudgeTime,
	checkInPast,
	checkInReopened,
	checkInStack,
	checkInStarted,
	checkInStep,
	checkInUnstarted,
	checkInWeek,
	DEFAULT_CHECK_IN_DAY,
	isCheckInDay,
	isWeekday,
	type PendingExtraIncome,
	WEEKDAYS,
	type Weekday,
	weekdayOf,
} from "./check-in";
export {
	comingUp,
	type Due,
	type DueStatus,
	duesBetween,
	type Lump,
	lumpsIn,
	lumpyMonths,
	type MatchedCharge,
	matchCharges,
} from "./coming-up";
export {
	COMMITMENT_KINDS,
	type CommitmentGroup,
	type CommitmentKind,
	commitmentKind,
	groupCommitments,
} from "./commitment-kinds";
export {
	ABOUT_DAYS,
	type AboutAmount,
	aboutAmount,
	byNextDue,
	CADENCES,
	type Cadence,
	type CommitmentTerms,
	dueDatesIn,
	expectedIn,
	monthlyEquivalent,
	nextDueDate,
	yearlyCost,
} from "./commitments";
export { type CoverSource, coverSources, leftToMove } from "./cover";
export {
	changeName,
	describeChange,
	type ScenarioChangeDescription,
	type ScenarioChangeSubjects,
	shortMonthName,
} from "./describe-changes";
export {
	countsOn,
	EXTRA_INCOME_FROM,
	type ExtraIncomeDestination,
	type ExtraIncomeSuggestion,
	extraIncomeOf,
	extraIncomeSuggestions,
	freeToSpendAfterLowering,
	INCOME_WARNING_FROM_DAY,
	type Income,
	type IncomeCheck,
	incomeCheck,
	LOWER_PAY_LAST_DAYS,
	type LowerTakeHomePay,
	lowerTakeHomePay,
	lowerTakeHomePayChange,
	receivedIn,
	type TakeHomePayJust,
	undoLowerTakeHomePay,
} from "./extra-income";
export {
	FEES_AND_INTEREST,
	type FeesOffer,
	feesBucketIn,
	feesOffer,
	feesRulePattern,
	interestEarned,
	looksLikeFeeOrInterest,
	looksLikeInterestEarned,
} from "./fees";
export * from "./file-holds";
export {
	type AttributedSpend,
	EVERYONE,
	type For,
	type ForTotals,
	forTotals,
	forWhom,
	LIKELY_FOR_AT_LEAST,
	LIKELY_FOR_LOOKS_AT,
	likelyFor,
	noForTotals,
	type SpendTotal,
	shareFor,
	shares,
	spendingFor,
} from "./for";
export {
	type CarryInputs,
	type FreeCarryMonth,
	firstCarryMonth,
	freeCarriedIn,
	freeCarryMonths,
	type MonthAmount,
} from "./free-carry";
export {
	allowancesByKind,
	freeToSpendParts,
	freeToSpendSources,
	type PlanPart,
} from "./free-to-spend";
export {
	ACCOUNT_KINDS,
	type AccountKind,
	type AccountWithdrawal,
	accountBalance,
	attributeWithdrawal,
	type BalanceUpdate,
	CARD_PAYMENT_DAYS,
	canPayOff,
	GOAL_KINDS,
	type GoalKind,
	type GoalProgress,
	type GoalStatus,
	goalBehindBy,
	goalHistory,
	goalProgress,
	holdsMoney,
	type OwedPayment,
	owedFor,
	owedOn,
	owedOverTime,
	type ProgressGoal,
	paidDownOf,
	payoffProgress,
	projectionGoalOf,
	type SetAsideChange,
	sentOnce,
	setAsideOf,
	splitAccount,
	stillToFund,
	type WithdrawalAttribution,
	withOwed,
} from "./goals";
export {
	accountForWalletCard,
	type BalanceCheck,
	balanceCheck,
	type CardKept,
	cardKept,
	cardKeptUnasked,
	cardPaymentIsSpending,
	PURCHASES_GET_IN,
	type PurchasesGetIn,
	STATEMENTS_FOLLOWED_DAYS,
	statementCheckDue,
	statementsFollowed,
	suggestedPurchases,
} from "./hand-kept";
export {
	findInsights,
	INSIGHT_KINDS,
	type InsightCandidate,
	type InsightInputs,
	type InsightKind,
	type InsightPerk,
	type InsightSpend,
	isOnce,
	isOverlap,
	RECURRING_DAYS,
	type Service,
	services,
} from "./insights";
export * from "./lean-month";
export {
	type LenderPayment,
	type LoanByAmount,
	type LoanFit,
	type LoanPaidDown,
	lenderPayment,
	loanByAmount,
	loansNamed,
	loansRuledByAmount,
	ruledLoanPayment,
} from "./lender-payments";
export {
	type BucketMatch,
	type BucketUse,
	hourAt,
	likelyBucketOrder,
	matchBuckets,
	type QuickAddChoice,
	type QuickAddReason,
	quickAddChoices,
} from "./likely";
export {
	dueDateOn,
	endedOrPaidOff,
	endsAfter,
	type LoanFacts,
	type LoanPayment,
	type LoanSchedule,
	loanInStep,
	loanPaid,
	loanPaidOffOn,
	loanSchedule,
	MAX_SCHEDULED_PAYMENTS,
	NO_LOAN_FACTS,
	nextLoanDue,
	type PaymentSchedule,
	type PaymentState,
	paymentSchedule,
	paymentsLeft,
	paymentsUntil,
	type ScheduledPayment,
	type SchedulePayment,
	scheduleFrom,
} from "./loans";
export {
	compareLogNames,
	LOG_EVENT_KINDS,
	LOG_ITEM_KINDS,
	LOG_PAIR_DETAIL,
	type LogCursor,
	type LogEventKind,
	type LogFreshStartStatus,
	type LogItemKind,
	type LogRow,
	type LogSnapshotKind,
	type LogSort,
	logItemOfEvent,
	logItemOfPlanChange,
	logWhen,
} from "./log";
export {
	autoMatches,
	clearPairs,
	MATCH_WINDOW,
	type MatchSide,
	merchantSimilarity,
	possibleMatches,
	withinMatchWindow,
} from "./matching";
export {
	bankMerchantKey,
	type CleanMerchant,
	cleanMerchant,
	displayMerchant,
	type MerchantNameBy,
	merchantGroup,
	merchantNameFor,
	plausibleMerchantName,
	ruleKeys,
} from "./merchant-name";
export { type Cents, MAX_CENTS, parseDollars } from "./money";
export * from "./money-in";
export {
	addDays,
	addMonths,
	type DayKey,
	dayKeyAt,
	daysBetween,
	daysInMonth,
	lastDayOf,
	type MonthKey,
	monthEnded,
	monthKeyAt,
	monthOfDay,
	monthsBetween,
} from "./month";
export {
	closeFreeMoveId,
	defaultDecision,
	fitsProposal,
	type Leftover,
	type MonthCloseDecision,
	type MonthCloseProposal,
	type MonthEnd,
	monthCloseProposal,
	monthEnd,
	nothingToClose,
	nothingToDecide,
	quietEnd,
} from "./month-close";
export {
	aboutCameIn,
	type BucketState,
	type BucketStatus,
	type Charge,
	type CommitmentState,
	type CommitmentStatus,
	type ExtraToFree,
	type GoalFunding,
	type MonthState,
	type Move,
	monthState,
	paymentsOf,
	paymentsView,
	type Spend,
	type Sweep,
} from "./month-state";
export {
	bucketsPassingPace,
	defaultNudgePreferences,
	isQuietAt,
	minuteOfDayAt,
	type NudgeKind,
	type NudgePreferences,
	nextLocalMinute,
	nudgeDeliveryTime,
	PACE_NUDGE_MIN_DAYS_LEFT,
	type QuietHours,
	wantsNudge,
} from "./nudges";
export { readOfxStatement } from "./ofx";
export {
	changeHoldsIn,
	type MonthBreakdown,
	monthBreakdown,
	type OutcomeWarning,
	outcomeWarnings,
	projectionAssumptions,
} from "./outcomes";
export * from "./owed-back";
export {
	canPair,
	type LineToPair,
	type PairableAccount,
	pairableFor,
	pairingScore,
	pairSameLines,
	SAME_LINE_DAYS,
	suggestPairings,
} from "./pairing";
export * from "./pay-days";
export * from "./pay-history";
export * from "./pay-plan-on";
export * from "./pay-range";
export * from "./pay-to-come";
export {
	PAYMENT_HISTORY_MONTHS,
	type PaymentLine,
	type PaymentSuggestion,
	paymentsTo,
	suggestPayment,
} from "./payment-history";
export * from "./perk-standing";
export * from "./perk-worth";
export {
	byPerkValue,
	type CatalogEntry,
	catalogEntryFor,
	detectPerkSources,
	earnRate,
	type FoundPerk,
	mentions,
	PERK_CATEGORIES,
	PERK_DETECT_DAYS,
	PERK_KINDS,
	PERK_RECHECK_DAYS,
	PERK_SOURCE_CATALOG,
	PERK_SOURCE_KINDS,
	type PerkCategory,
	type PerkKind,
	type PerkSourceKind,
	type PerkSourceSuggestion,
	type PerkSpend,
	perkCategory,
	perkCategoryLabel,
	perkKey,
	perkSourceKindLabel,
	perksForPlan,
	perksOnPage,
	plainWords,
} from "./perks";
export {
	type BucketRecord,
	type CommitmentRecord,
	canAssign,
	commitmentsIn,
	firstPlanMonth,
	freeToSpend,
	type Plan,
	type PlanBucket,
	type PlanCommitment,
	type PlanRecords,
	planForMonth,
	totalAllowances,
	totalCommitments,
} from "./plan";
export {
	type DetectedCommitment,
	DRAFT_BUCKET_NAMES,
	DRAFT_DAYS,
	DRAFT_MIN_DAYS,
	type DraftBucket,
	type DraftCommitment,
	type DraftFindings,
	type DraftHistory,
	type DraftIncome,
	type DraftLabels,
	type DraftMerchant,
	type DraftTakeHomePay,
	detectCommitments,
	detectPaychecks,
	draftFindings,
	draftIsEmpty,
	draftPlan,
	draftVaries,
	EVERYDAY_BUCKET,
	MAX_DRAFT_MERCHANTS,
	merchantsToLabel,
	noDraftLabels,
	type PayCadence,
	type Paycheck,
	type PlanDraft,
	type PlanSoFar,
	plainName,
	suggestBuckets,
} from "./plan-draft";
export {
	byUrgency,
	cardsNowFollowed,
	HEALTH_HABIT_MONTHS,
	HEALTH_MONTHS_AHEAD,
	type HealthCard,
	type HealthGoal,
	type PlanWarning,
	planHealth,
} from "./plan-health";
export {
	PLAN_CHANGE_KINDS,
	type PlanChange,
	type PlanChangeKind,
	type PlanChangeSource,
	type PlanChangeValue,
} from "./plan-history";
export { type PlanChanges, type PlanScope, planChanges, restoreAfterJust } from "./plan-scope";
export {
	canApply,
	parseReceiptAmount,
	proposeSplits,
	RECEIPT_DATE_WINDOW_DAYS,
	type ReceiptLine,
	type ReceiptLineKind,
	type ReceiptPart,
	type ReceiptProposal,
	receiptDate,
	receiptDifference,
	receiptLine,
	receiptTransaction,
	shareOut,
} from "./receipts";
export {
	type AmountBand,
	addMonthsToDay,
	COMPARISONS,
	type Comparison,
	cashFlow,
	changeOf,
	comparisonRange,
	csvDollars,
	type DayRange,
	defaultGrouping,
	type Flow,
	type ForCell,
	freeToSpendOver,
	GROUPINGS,
	type Grouping,
	headlines,
	incomeByMonth,
	levelOf,
	mergeCells,
	monthsIn,
	overThreshold,
	owedAtEndOf,
	paidDownHistory,
	periodKey,
	periodKeys,
	periodRange,
	periodStart,
	planHabits,
	planVsActual,
	projectedCompletion,
	projectedPayoff,
	REPORT_PERIODS,
	type ReportPeriod,
	recurringSplit,
	regroupMonthly,
	type SpendCell,
	seriesOf,
	setAsideHistory,
	spendFor,
	sumOf,
	type Target,
	THRESHOLD_STOPS,
	targetId,
	targetKind,
	toCsv,
	topWithOther,
	totalsBy,
	type Variance,
	withinHistory,
} from "./reports";
export {
	type BucketMonth,
	bucketMonths,
	type MonthlySpend,
	rolledOver,
	rolloverSince,
} from "./rollover";
export {
	changeImpacts,
	MAX_PROJECTION_MONTHS,
	moneyFreed,
	type PlanAhead,
	type ProjectedGoal,
	type ProjectedMonth,
	type Projection,
	type ProjectionGoal,
	type ProjectOptions,
	planAhead,
	project,
	type ScenarioChangeImpact,
} from "./scenario";
export {
	type AssignedTransaction,
	type Assignment,
	assignedParts,
	type GoalSpend,
	type Split,
	type SplitAssignment,
	splitRemainder,
	splitsBalance,
} from "./splits";
export { findSpokenAmount, parseSpokenAmount, spokenAmount } from "./spoken";
export { readStatement } from "./statement-file";
export {
	type ClosingBalance,
	type CsvMapping,
	closingBalanceFor,
	DATE_FORMATS,
	type DateFormat,
	guessCsvMapping,
	guessDateFormat,
	normalizeDescription,
	parseCsv,
	parseStatementAmount,
	parseStatementDate,
	readCsvStatement,
	type Statement,
	type StatementFormat,
	type StatementLine,
	statementFormat,
	statementLineIds,
} from "./statements";
export * from "./suggestions";
export {
	likelyCardPayment,
	likelyOriginals,
	looksLikeCardPayment,
	type PayingCommitment,
	type PaymentAccount,
	type PaymentCase,
	paymentCase,
	REFUND_WINDOW_DAYS,
	type RefundSide,
	readsAsPaymentReceived,
	TRANSFER_WINDOW_DAYS,
	type TransferSide,
	transferPairs,
} from "./transfers";
export {
	actualFigures,
	type YearActuals,
	type YearFigures,
	type YearMonth,
	yearGrid,
} from "./year";
