/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedHouseholdRouteImport } from './routes/_authed/_household'
import { Route as AuthedWelcomeRouteImport } from './routes/_authed/welcome'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthedHouseholdAskRouteImport } from './routes/_authed/_household/ask'
import { Route as AuthedHouseholdCheckInRouteImport } from './routes/_authed/_household/check-in'
import { Route as AuthedHouseholdExploreRouteImport } from './routes/_authed/_household/explore'
import { Route as AuthedHouseholdHouseholdRouteImport } from './routes/_authed/_household/household'
import { Route as AuthedHouseholdInsightsRouteImport } from './routes/_authed/_household/insights'
import { Route as AuthedHouseholdPerksRouteImport } from './routes/_authed/_household/perks'
import { Route as AuthedHouseholdReportsRouteImport } from './routes/_authed/_household/reports'
import { Route as AuthedHouseholdAccountsIndexRouteImport } from './routes/_authed/_household/accounts.index'
import { Route as AuthedHouseholdAccountsAccountIdRouteImport } from './routes/_authed/_household/accounts.$accountId'
import { Route as AuthedHouseholdExploreAffordRouteImport } from './routes/_authed/_household/explore_.afford'
import { Route as AuthedHouseholdExploreScenariosRouteImport } from './routes/_authed/_household/explore_.scenarios'
import { Route as AuthedHouseholdGoalsIndexRouteImport } from './routes/_authed/_household/goals.index'
import { Route as AuthedHouseholdGoalsGoalIdRouteImport } from './routes/_authed/_household/goals.$goalId'
import { Route as AuthedHouseholdMonthIndexRouteImport } from './routes/_authed/_household/month.index'
import { Route as AuthedHouseholdMonthMonthRouteImport } from './routes/_authed/_household/month.$month'
import { Route as AuthedHouseholdPlanIndexRouteImport } from './routes/_authed/_household/plan.index'
import { Route as AuthedHouseholdPlanMonthRouteImport } from './routes/_authed/_household/plan.$month'
import { Route as AuthedHouseholdReviewIndexRouteImport } from './routes/_authed/_household/review.index'
import { Route as AuthedHouseholdReviewRulesRouteImport } from './routes/_authed/_household/review.rules'
import { Route as AuthedHouseholdTransactionsIndexRouteImport } from './routes/_authed/_household/transactions.index'
import { Route as AuthedHouseholdTransactionsMonthRouteImport } from './routes/_authed/_household/transactions.$month'
import { Route as AuthedHouseholdGoalsAccountsAccountIdRouteImport } from './routes/_authed/_household/goals.accounts.$accountId'
import { Route as AuthedHouseholdMonthMonthIndexRouteImport } from './routes/_authed/_household/month.$month.index'
import { Route as AuthedHouseholdMonthMonthPlanRouteImport } from './routes/_authed/_household/month.$month.plan'
import { Route as AuthedHouseholdPlanMonthIndexRouteImport } from './routes/_authed/_household/plan.$month.index'
import { Route as AuthedHouseholdPlanMonthBucketsRouteImport } from './routes/_authed/_household/plan.$month.buckets'
import { Route as AuthedHouseholdPlanMonthCommitmentsRouteImport } from './routes/_authed/_household/plan.$month.commitments'
import { Route as AuthedHouseholdPlanMonthGoalsRouteImport } from './routes/_authed/_household/plan.$month.goals'
import { Route as AuthedHouseholdPlanMonthIncomeRouteImport } from './routes/_authed/_household/plan.$month.income'
import { Route as AuthedHouseholdPlanBucketsIdRouteImport } from './routes/_authed/_household/plan.buckets.$id'
import { Route as AuthedHouseholdPlanCommitmentsIdRouteImport } from './routes/_authed/_household/plan.commitments.$id'
import { Route as AuthedHouseholdPlanYearYearRouteImport } from './routes/_authed/_household/plan.year.$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHouseholdRoute = AuthedHouseholdRouteImport.update({
  id: '/_household',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWelcomeRoute = AuthedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthedRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHouseholdAskRoute = AuthedHouseholdAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdCheckInRoute = AuthedHouseholdCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdExploreRoute = AuthedHouseholdExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdHouseholdRoute =
  AuthedHouseholdHouseholdRouteImport.update({
    id: '/household',
    path: '/household',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdInsightsRoute = AuthedHouseholdInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdPerksRoute = AuthedHouseholdPerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdReportsRoute = AuthedHouseholdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdAccountsIndexRoute =
  AuthedHouseholdAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdAccountsAccountIdRoute =
  AuthedHouseholdAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdExploreAffordRoute =
  AuthedHouseholdExploreAffordRouteImport.update({
    id: '/explore_/afford',
    path: '/explore/afford',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdExploreScenariosRoute =
  AuthedHouseholdExploreScenariosRouteImport.update({
    id: '/explore_/scenarios',
    path: '/explore/scenarios',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdGoalsIndexRoute =
  AuthedHouseholdGoalsIndexRouteImport.update({
    id: '/goals/',
    path: '/goals/',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdGoalsGoalIdRoute =
  AuthedHouseholdGoalsGoalIdRouteImport.update({
    id: '/goals/$goalId',
    path: '/goals/$goalId',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdMonthIndexRoute =
  AuthedHouseholdMonthIndexRouteImport.update({
    id: '/month/',
    path: '/month/',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdMonthMonthRoute =
  AuthedHouseholdMonthMonthRouteImport.update({
    id: '/month/$month',
    path: '/month/$month',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdPlanIndexRoute =
  AuthedHouseholdPlanIndexRouteImport.update({
    id: '/plan/',
    path: '/plan/',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdPlanMonthRoute =
  AuthedHouseholdPlanMonthRouteImport.update({
    id: '/plan/$month',
    path: '/plan/$month',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdReviewIndexRoute =
  AuthedHouseholdReviewIndexRouteImport.update({
    id: '/review/',
    path: '/review/',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdReviewRulesRoute =
  AuthedHouseholdReviewRulesRouteImport.update({
    id: '/review/rules',
    path: '/review/rules',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdTransactionsIndexRoute =
  AuthedHouseholdTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdTransactionsMonthRoute =
  AuthedHouseholdTransactionsMonthRouteImport.update({
    id: '/transactions/$month',
    path: '/transactions/$month',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdGoalsAccountsAccountIdRoute =
  AuthedHouseholdGoalsAccountsAccountIdRouteImport.update({
    id: '/goals/accounts/$accountId',
    path: '/goals/accounts/$accountId',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdMonthMonthIndexRoute =
  AuthedHouseholdMonthMonthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedHouseholdMonthMonthRoute,
  } as any)
const AuthedHouseholdMonthMonthPlanRoute =
  AuthedHouseholdMonthMonthPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AuthedHouseholdMonthMonthRoute,
  } as any)
const AuthedHouseholdPlanMonthIndexRoute =
  AuthedHouseholdPlanMonthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedHouseholdPlanMonthRoute,
  } as any)
const AuthedHouseholdPlanMonthBucketsRoute =
  AuthedHouseholdPlanMonthBucketsRouteImport.update({
    id: '/buckets',
    path: '/buckets',
    getParentRoute: () => AuthedHouseholdPlanMonthRoute,
  } as any)
const AuthedHouseholdPlanMonthCommitmentsRoute =
  AuthedHouseholdPlanMonthCommitmentsRouteImport.update({
    id: '/commitments',
    path: '/commitments',
    getParentRoute: () => AuthedHouseholdPlanMonthRoute,
  } as any)
const AuthedHouseholdPlanMonthGoalsRoute =
  AuthedHouseholdPlanMonthGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => AuthedHouseholdPlanMonthRoute,
  } as any)
const AuthedHouseholdPlanMonthIncomeRoute =
  AuthedHouseholdPlanMonthIncomeRouteImport.update({
    id: '/income',
    path: '/income',
    getParentRoute: () => AuthedHouseholdPlanMonthRoute,
  } as any)
const AuthedHouseholdPlanBucketsIdRoute =
  AuthedHouseholdPlanBucketsIdRouteImport.update({
    id: '/plan/buckets/$id',
    path: '/plan/buckets/$id',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdPlanCommitmentsIdRoute =
  AuthedHouseholdPlanCommitmentsIdRouteImport.update({
    id: '/plan/commitments/$id',
    path: '/plan/commitments/$id',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdPlanYearYearRoute =
  AuthedHouseholdPlanYearYearRouteImport.update({
    id: '/plan/year/$year',
    path: '/plan/year/$year',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/ask': typeof AuthedHouseholdAskRoute
  '/check-in': typeof AuthedHouseholdCheckInRoute
  '/explore': typeof AuthedHouseholdExploreRoute
  '/household': typeof AuthedHouseholdHouseholdRoute
  '/insights': typeof AuthedHouseholdInsightsRoute
  '/perks': typeof AuthedHouseholdPerksRoute
  '/reports': typeof AuthedHouseholdReportsRoute
  '/accounts/$accountId': typeof AuthedHouseholdAccountsAccountIdRoute
  '/explore/afford': typeof AuthedHouseholdExploreAffordRoute
  '/explore/scenarios': typeof AuthedHouseholdExploreScenariosRoute
  '/goals/$goalId': typeof AuthedHouseholdGoalsGoalIdRoute
  '/month/$month': typeof AuthedHouseholdMonthMonthRouteWithChildren
  '/plan/$month': typeof AuthedHouseholdPlanMonthRouteWithChildren
  '/review/rules': typeof AuthedHouseholdReviewRulesRoute
  '/transactions/$month': typeof AuthedHouseholdTransactionsMonthRoute
  '/accounts/': typeof AuthedHouseholdAccountsIndexRoute
  '/goals/': typeof AuthedHouseholdGoalsIndexRoute
  '/month/': typeof AuthedHouseholdMonthIndexRoute
  '/plan/': typeof AuthedHouseholdPlanIndexRoute
  '/review/': typeof AuthedHouseholdReviewIndexRoute
  '/transactions/': typeof AuthedHouseholdTransactionsIndexRoute
  '/goals/accounts/$accountId': typeof AuthedHouseholdGoalsAccountsAccountIdRoute
  '/month/$month/plan': typeof AuthedHouseholdMonthMonthPlanRoute
  '/plan/$month/buckets': typeof AuthedHouseholdPlanMonthBucketsRoute
  '/plan/$month/commitments': typeof AuthedHouseholdPlanMonthCommitmentsRoute
  '/plan/$month/goals': typeof AuthedHouseholdPlanMonthGoalsRoute
  '/plan/$month/income': typeof AuthedHouseholdPlanMonthIncomeRoute
  '/plan/buckets/$id': typeof AuthedHouseholdPlanBucketsIdRoute
  '/plan/commitments/$id': typeof AuthedHouseholdPlanCommitmentsIdRoute
  '/plan/year/$year': typeof AuthedHouseholdPlanYearYearRoute
  '/month/$month/': typeof AuthedHouseholdMonthMonthIndexRoute
  '/plan/$month/': typeof AuthedHouseholdPlanMonthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/ask': typeof AuthedHouseholdAskRoute
  '/check-in': typeof AuthedHouseholdCheckInRoute
  '/explore': typeof AuthedHouseholdExploreRoute
  '/household': typeof AuthedHouseholdHouseholdRoute
  '/insights': typeof AuthedHouseholdInsightsRoute
  '/perks': typeof AuthedHouseholdPerksRoute
  '/reports': typeof AuthedHouseholdReportsRoute
  '/accounts/$accountId': typeof AuthedHouseholdAccountsAccountIdRoute
  '/explore/afford': typeof AuthedHouseholdExploreAffordRoute
  '/explore/scenarios': typeof AuthedHouseholdExploreScenariosRoute
  '/goals/$goalId': typeof AuthedHouseholdGoalsGoalIdRoute
  '/review/rules': typeof AuthedHouseholdReviewRulesRoute
  '/transactions/$month': typeof AuthedHouseholdTransactionsMonthRoute
  '/accounts': typeof AuthedHouseholdAccountsIndexRoute
  '/goals': typeof AuthedHouseholdGoalsIndexRoute
  '/month': typeof AuthedHouseholdMonthIndexRoute
  '/plan': typeof AuthedHouseholdPlanIndexRoute
  '/review': typeof AuthedHouseholdReviewIndexRoute
  '/transactions': typeof AuthedHouseholdTransactionsIndexRoute
  '/goals/accounts/$accountId': typeof AuthedHouseholdGoalsAccountsAccountIdRoute
  '/month/$month/plan': typeof AuthedHouseholdMonthMonthPlanRoute
  '/plan/$month/buckets': typeof AuthedHouseholdPlanMonthBucketsRoute
  '/plan/$month/commitments': typeof AuthedHouseholdPlanMonthCommitmentsRoute
  '/plan/$month/goals': typeof AuthedHouseholdPlanMonthGoalsRoute
  '/plan/$month/income': typeof AuthedHouseholdPlanMonthIncomeRoute
  '/plan/buckets/$id': typeof AuthedHouseholdPlanBucketsIdRoute
  '/plan/commitments/$id': typeof AuthedHouseholdPlanCommitmentsIdRoute
  '/plan/year/$year': typeof AuthedHouseholdPlanYearYearRoute
  '/month/$month': typeof AuthedHouseholdMonthMonthIndexRoute
  '/plan/$month': typeof AuthedHouseholdPlanMonthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/_household': typeof AuthedHouseholdRouteWithChildren
  '/_authed/welcome': typeof AuthedWelcomeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/_authed/_household/ask': typeof AuthedHouseholdAskRoute
  '/_authed/_household/check-in': typeof AuthedHouseholdCheckInRoute
  '/_authed/_household/explore': typeof AuthedHouseholdExploreRoute
  '/_authed/_household/household': typeof AuthedHouseholdHouseholdRoute
  '/_authed/_household/insights': typeof AuthedHouseholdInsightsRoute
  '/_authed/_household/perks': typeof AuthedHouseholdPerksRoute
  '/_authed/_household/reports': typeof AuthedHouseholdReportsRoute
  '/_authed/_household/accounts/$accountId': typeof AuthedHouseholdAccountsAccountIdRoute
  '/_authed/_household/explore_/afford': typeof AuthedHouseholdExploreAffordRoute
  '/_authed/_household/explore_/scenarios': typeof AuthedHouseholdExploreScenariosRoute
  '/_authed/_household/goals/$goalId': typeof AuthedHouseholdGoalsGoalIdRoute
  '/_authed/_household/month/$month': typeof AuthedHouseholdMonthMonthRouteWithChildren
  '/_authed/_household/plan/$month': typeof AuthedHouseholdPlanMonthRouteWithChildren
  '/_authed/_household/review/rules': typeof AuthedHouseholdReviewRulesRoute
  '/_authed/_household/transactions/$month': typeof AuthedHouseholdTransactionsMonthRoute
  '/_authed/_household/accounts/': typeof AuthedHouseholdAccountsIndexRoute
  '/_authed/_household/goals/': typeof AuthedHouseholdGoalsIndexRoute
  '/_authed/_household/month/': typeof AuthedHouseholdMonthIndexRoute
  '/_authed/_household/plan/': typeof AuthedHouseholdPlanIndexRoute
  '/_authed/_household/review/': typeof AuthedHouseholdReviewIndexRoute
  '/_authed/_household/transactions/': typeof AuthedHouseholdTransactionsIndexRoute
  '/_authed/_household/goals/accounts/$accountId': typeof AuthedHouseholdGoalsAccountsAccountIdRoute
  '/_authed/_household/month/$month/plan': typeof AuthedHouseholdMonthMonthPlanRoute
  '/_authed/_household/plan/$month/buckets': typeof AuthedHouseholdPlanMonthBucketsRoute
  '/_authed/_household/plan/$month/commitments': typeof AuthedHouseholdPlanMonthCommitmentsRoute
  '/_authed/_household/plan/$month/goals': typeof AuthedHouseholdPlanMonthGoalsRoute
  '/_authed/_household/plan/$month/income': typeof AuthedHouseholdPlanMonthIncomeRoute
  '/_authed/_household/plan/buckets/$id': typeof AuthedHouseholdPlanBucketsIdRoute
  '/_authed/_household/plan/commitments/$id': typeof AuthedHouseholdPlanCommitmentsIdRoute
  '/_authed/_household/plan/year/$year': typeof AuthedHouseholdPlanYearYearRoute
  '/_authed/_household/month/$month/': typeof AuthedHouseholdMonthMonthIndexRoute
  '/_authed/_household/plan/$month/': typeof AuthedHouseholdPlanMonthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/sign-in/$'
    | '/ask'
    | '/check-in'
    | '/explore'
    | '/household'
    | '/insights'
    | '/perks'
    | '/reports'
    | '/accounts/$accountId'
    | '/explore/afford'
    | '/explore/scenarios'
    | '/goals/$goalId'
    | '/month/$month'
    | '/plan/$month'
    | '/review/rules'
    | '/transactions/$month'
    | '/accounts/'
    | '/goals/'
    | '/month/'
    | '/plan/'
    | '/review/'
    | '/transactions/'
    | '/goals/accounts/$accountId'
    | '/month/$month/plan'
    | '/plan/$month/buckets'
    | '/plan/$month/commitments'
    | '/plan/$month/goals'
    | '/plan/$month/income'
    | '/plan/buckets/$id'
    | '/plan/commitments/$id'
    | '/plan/year/$year'
    | '/month/$month/'
    | '/plan/$month/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/sign-in/$'
    | '/ask'
    | '/check-in'
    | '/explore'
    | '/household'
    | '/insights'
    | '/perks'
    | '/reports'
    | '/accounts/$accountId'
    | '/explore/afford'
    | '/explore/scenarios'
    | '/goals/$goalId'
    | '/review/rules'
    | '/transactions/$month'
    | '/accounts'
    | '/goals'
    | '/month'
    | '/plan'
    | '/review'
    | '/transactions'
    | '/goals/accounts/$accountId'
    | '/month/$month/plan'
    | '/plan/$month/buckets'
    | '/plan/$month/commitments'
    | '/plan/$month/goals'
    | '/plan/$month/income'
    | '/plan/buckets/$id'
    | '/plan/commitments/$id'
    | '/plan/year/$year'
    | '/month/$month'
    | '/plan/$month'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/_household'
    | '/_authed/welcome'
    | '/sign-in/$'
    | '/_authed/_household/ask'
    | '/_authed/_household/check-in'
    | '/_authed/_household/explore'
    | '/_authed/_household/household'
    | '/_authed/_household/insights'
    | '/_authed/_household/perks'
    | '/_authed/_household/reports'
    | '/_authed/_household/accounts/$accountId'
    | '/_authed/_household/explore_/afford'
    | '/_authed/_household/explore_/scenarios'
    | '/_authed/_household/goals/$goalId'
    | '/_authed/_household/month/$month'
    | '/_authed/_household/plan/$month'
    | '/_authed/_household/review/rules'
    | '/_authed/_household/transactions/$month'
    | '/_authed/_household/accounts/'
    | '/_authed/_household/goals/'
    | '/_authed/_household/month/'
    | '/_authed/_household/plan/'
    | '/_authed/_household/review/'
    | '/_authed/_household/transactions/'
    | '/_authed/_household/goals/accounts/$accountId'
    | '/_authed/_household/month/$month/plan'
    | '/_authed/_household/plan/$month/buckets'
    | '/_authed/_household/plan/$month/commitments'
    | '/_authed/_household/plan/$month/goals'
    | '/_authed/_household/plan/$month/income'
    | '/_authed/_household/plan/buckets/$id'
    | '/_authed/_household/plan/commitments/$id'
    | '/_authed/_household/plan/year/$year'
    | '/_authed/_household/month/$month/'
    | '/_authed/_household/plan/$month/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_household': {
      id: '/_authed/_household'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedHouseholdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/welcome': {
      id: '/_authed/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthedWelcomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_household/ask': {
      id: '/_authed/_household/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthedHouseholdAskRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/check-in': {
      id: '/_authed/_household/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthedHouseholdCheckInRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/explore': {
      id: '/_authed/_household/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthedHouseholdExploreRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/household': {
      id: '/_authed/_household/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AuthedHouseholdHouseholdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/insights': {
      id: '/_authed/_household/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthedHouseholdInsightsRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/perks': {
      id: '/_authed/_household/perks'
      path: '/perks'
      fullPath: '/perks'
      preLoaderRoute: typeof AuthedHouseholdPerksRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/reports': {
      id: '/_authed/_household/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedHouseholdReportsRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/accounts/': {
      id: '/_authed/_household/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthedHouseholdAccountsIndexRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/accounts/$accountId': {
      id: '/_authed/_household/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthedHouseholdAccountsAccountIdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/explore_/afford': {
      id: '/_authed/_household/explore_/afford'
      path: '/explore/afford'
      fullPath: '/explore/afford'
      preLoaderRoute: typeof AuthedHouseholdExploreAffordRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/explore_/scenarios': {
      id: '/_authed/_household/explore_/scenarios'
      path: '/explore/scenarios'
      fullPath: '/explore/scenarios'
      preLoaderRoute: typeof AuthedHouseholdExploreScenariosRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/goals/': {
      id: '/_authed/_household/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AuthedHouseholdGoalsIndexRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/goals/$goalId': {
      id: '/_authed/_household/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof AuthedHouseholdGoalsGoalIdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/month/': {
      id: '/_authed/_household/month/'
      path: '/month'
      fullPath: '/month/'
      preLoaderRoute: typeof AuthedHouseholdMonthIndexRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/month/$month': {
      id: '/_authed/_household/month/$month'
      path: '/month/$month'
      fullPath: '/month/$month'
      preLoaderRoute: typeof AuthedHouseholdMonthMonthRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/plan/': {
      id: '/_authed/_household/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof AuthedHouseholdPlanIndexRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/plan/$month': {
      id: '/_authed/_household/plan/$month'
      path: '/plan/$month'
      fullPath: '/plan/$month'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/review/': {
      id: '/_authed/_household/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof AuthedHouseholdReviewIndexRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/review/rules': {
      id: '/_authed/_household/review/rules'
      path: '/review/rules'
      fullPath: '/review/rules'
      preLoaderRoute: typeof AuthedHouseholdReviewRulesRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/transactions/': {
      id: '/_authed/_household/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthedHouseholdTransactionsIndexRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/transactions/$month': {
      id: '/_authed/_household/transactions/$month'
      path: '/transactions/$month'
      fullPath: '/transactions/$month'
      preLoaderRoute: typeof AuthedHouseholdTransactionsMonthRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/goals/accounts/$accountId': {
      id: '/_authed/_household/goals/accounts/$accountId'
      path: '/goals/accounts/$accountId'
      fullPath: '/goals/accounts/$accountId'
      preLoaderRoute: typeof AuthedHouseholdGoalsAccountsAccountIdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/month/$month/': {
      id: '/_authed/_household/month/$month/'
      path: '/'
      fullPath: '/month/$month/'
      preLoaderRoute: typeof AuthedHouseholdMonthMonthIndexRouteImport
      parentRoute: typeof AuthedHouseholdMonthMonthRoute
    }
    '/_authed/_household/month/$month/plan': {
      id: '/_authed/_household/month/$month/plan'
      path: '/plan'
      fullPath: '/month/$month/plan'
      preLoaderRoute: typeof AuthedHouseholdMonthMonthPlanRouteImport
      parentRoute: typeof AuthedHouseholdMonthMonthRoute
    }
    '/_authed/_household/plan/$month/': {
      id: '/_authed/_household/plan/$month/'
      path: '/'
      fullPath: '/plan/$month/'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthIndexRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthRoute
    }
    '/_authed/_household/plan/$month/buckets': {
      id: '/_authed/_household/plan/$month/buckets'
      path: '/buckets'
      fullPath: '/plan/$month/buckets'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthBucketsRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthRoute
    }
    '/_authed/_household/plan/$month/commitments': {
      id: '/_authed/_household/plan/$month/commitments'
      path: '/commitments'
      fullPath: '/plan/$month/commitments'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthCommitmentsRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthRoute
    }
    '/_authed/_household/plan/$month/goals': {
      id: '/_authed/_household/plan/$month/goals'
      path: '/goals'
      fullPath: '/plan/$month/goals'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthGoalsRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthRoute
    }
    '/_authed/_household/plan/$month/income': {
      id: '/_authed/_household/plan/$month/income'
      path: '/income'
      fullPath: '/plan/$month/income'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthIncomeRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthRoute
    }
    '/_authed/_household/plan/buckets/$id': {
      id: '/_authed/_household/plan/buckets/$id'
      path: '/plan/buckets/$id'
      fullPath: '/plan/buckets/$id'
      preLoaderRoute: typeof AuthedHouseholdPlanBucketsIdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/plan/commitments/$id': {
      id: '/_authed/_household/plan/commitments/$id'
      path: '/plan/commitments/$id'
      fullPath: '/plan/commitments/$id'
      preLoaderRoute: typeof AuthedHouseholdPlanCommitmentsIdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/plan/year/$year': {
      id: '/_authed/_household/plan/year/$year'
      path: '/plan/year/$year'
      fullPath: '/plan/year/$year'
      preLoaderRoute: typeof AuthedHouseholdPlanYearYearRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
  }
}

interface AuthedHouseholdMonthMonthRouteChildren {
  AuthedHouseholdMonthMonthPlanRoute: typeof AuthedHouseholdMonthMonthPlanRoute
  AuthedHouseholdMonthMonthIndexRoute: typeof AuthedHouseholdMonthMonthIndexRoute
}

const AuthedHouseholdMonthMonthRouteChildren: AuthedHouseholdMonthMonthRouteChildren =
  {
    AuthedHouseholdMonthMonthPlanRoute: AuthedHouseholdMonthMonthPlanRoute,
    AuthedHouseholdMonthMonthIndexRoute: AuthedHouseholdMonthMonthIndexRoute,
  }

const AuthedHouseholdMonthMonthRouteWithChildren =
  AuthedHouseholdMonthMonthRoute._addFileChildren(
    AuthedHouseholdMonthMonthRouteChildren,
  )

interface AuthedHouseholdPlanMonthRouteChildren {
  AuthedHouseholdPlanMonthBucketsRoute: typeof AuthedHouseholdPlanMonthBucketsRoute
  AuthedHouseholdPlanMonthCommitmentsRoute: typeof AuthedHouseholdPlanMonthCommitmentsRoute
  AuthedHouseholdPlanMonthGoalsRoute: typeof AuthedHouseholdPlanMonthGoalsRoute
  AuthedHouseholdPlanMonthIncomeRoute: typeof AuthedHouseholdPlanMonthIncomeRoute
  AuthedHouseholdPlanMonthIndexRoute: typeof AuthedHouseholdPlanMonthIndexRoute
}

const AuthedHouseholdPlanMonthRouteChildren: AuthedHouseholdPlanMonthRouteChildren =
  {
    AuthedHouseholdPlanMonthBucketsRoute: AuthedHouseholdPlanMonthBucketsRoute,
    AuthedHouseholdPlanMonthCommitmentsRoute:
      AuthedHouseholdPlanMonthCommitmentsRoute,
    AuthedHouseholdPlanMonthGoalsRoute: AuthedHouseholdPlanMonthGoalsRoute,
    AuthedHouseholdPlanMonthIncomeRoute: AuthedHouseholdPlanMonthIncomeRoute,
    AuthedHouseholdPlanMonthIndexRoute: AuthedHouseholdPlanMonthIndexRoute,
  }

const AuthedHouseholdPlanMonthRouteWithChildren =
  AuthedHouseholdPlanMonthRoute._addFileChildren(
    AuthedHouseholdPlanMonthRouteChildren,
  )

interface AuthedHouseholdRouteChildren {
  AuthedHouseholdAskRoute: typeof AuthedHouseholdAskRoute
  AuthedHouseholdCheckInRoute: typeof AuthedHouseholdCheckInRoute
  AuthedHouseholdExploreRoute: typeof AuthedHouseholdExploreRoute
  AuthedHouseholdHouseholdRoute: typeof AuthedHouseholdHouseholdRoute
  AuthedHouseholdInsightsRoute: typeof AuthedHouseholdInsightsRoute
  AuthedHouseholdPerksRoute: typeof AuthedHouseholdPerksRoute
  AuthedHouseholdReportsRoute: typeof AuthedHouseholdReportsRoute
  AuthedHouseholdAccountsAccountIdRoute: typeof AuthedHouseholdAccountsAccountIdRoute
  AuthedHouseholdExploreAffordRoute: typeof AuthedHouseholdExploreAffordRoute
  AuthedHouseholdExploreScenariosRoute: typeof AuthedHouseholdExploreScenariosRoute
  AuthedHouseholdGoalsGoalIdRoute: typeof AuthedHouseholdGoalsGoalIdRoute
  AuthedHouseholdMonthMonthRoute: typeof AuthedHouseholdMonthMonthRouteWithChildren
  AuthedHouseholdPlanMonthRoute: typeof AuthedHouseholdPlanMonthRouteWithChildren
  AuthedHouseholdReviewRulesRoute: typeof AuthedHouseholdReviewRulesRoute
  AuthedHouseholdTransactionsMonthRoute: typeof AuthedHouseholdTransactionsMonthRoute
  AuthedHouseholdAccountsIndexRoute: typeof AuthedHouseholdAccountsIndexRoute
  AuthedHouseholdGoalsIndexRoute: typeof AuthedHouseholdGoalsIndexRoute
  AuthedHouseholdMonthIndexRoute: typeof AuthedHouseholdMonthIndexRoute
  AuthedHouseholdPlanIndexRoute: typeof AuthedHouseholdPlanIndexRoute
  AuthedHouseholdReviewIndexRoute: typeof AuthedHouseholdReviewIndexRoute
  AuthedHouseholdTransactionsIndexRoute: typeof AuthedHouseholdTransactionsIndexRoute
  AuthedHouseholdGoalsAccountsAccountIdRoute: typeof AuthedHouseholdGoalsAccountsAccountIdRoute
  AuthedHouseholdPlanBucketsIdRoute: typeof AuthedHouseholdPlanBucketsIdRoute
  AuthedHouseholdPlanCommitmentsIdRoute: typeof AuthedHouseholdPlanCommitmentsIdRoute
  AuthedHouseholdPlanYearYearRoute: typeof AuthedHouseholdPlanYearYearRoute
}

const AuthedHouseholdRouteChildren: AuthedHouseholdRouteChildren = {
  AuthedHouseholdAskRoute: AuthedHouseholdAskRoute,
  AuthedHouseholdCheckInRoute: AuthedHouseholdCheckInRoute,
  AuthedHouseholdExploreRoute: AuthedHouseholdExploreRoute,
  AuthedHouseholdHouseholdRoute: AuthedHouseholdHouseholdRoute,
  AuthedHouseholdInsightsRoute: AuthedHouseholdInsightsRoute,
  AuthedHouseholdPerksRoute: AuthedHouseholdPerksRoute,
  AuthedHouseholdReportsRoute: AuthedHouseholdReportsRoute,
  AuthedHouseholdAccountsAccountIdRoute: AuthedHouseholdAccountsAccountIdRoute,
  AuthedHouseholdExploreAffordRoute: AuthedHouseholdExploreAffordRoute,
  AuthedHouseholdExploreScenariosRoute: AuthedHouseholdExploreScenariosRoute,
  AuthedHouseholdGoalsGoalIdRoute: AuthedHouseholdGoalsGoalIdRoute,
  AuthedHouseholdMonthMonthRoute: AuthedHouseholdMonthMonthRouteWithChildren,
  AuthedHouseholdPlanMonthRoute: AuthedHouseholdPlanMonthRouteWithChildren,
  AuthedHouseholdReviewRulesRoute: AuthedHouseholdReviewRulesRoute,
  AuthedHouseholdTransactionsMonthRoute: AuthedHouseholdTransactionsMonthRoute,
  AuthedHouseholdAccountsIndexRoute: AuthedHouseholdAccountsIndexRoute,
  AuthedHouseholdGoalsIndexRoute: AuthedHouseholdGoalsIndexRoute,
  AuthedHouseholdMonthIndexRoute: AuthedHouseholdMonthIndexRoute,
  AuthedHouseholdPlanIndexRoute: AuthedHouseholdPlanIndexRoute,
  AuthedHouseholdReviewIndexRoute: AuthedHouseholdReviewIndexRoute,
  AuthedHouseholdTransactionsIndexRoute: AuthedHouseholdTransactionsIndexRoute,
  AuthedHouseholdGoalsAccountsAccountIdRoute:
    AuthedHouseholdGoalsAccountsAccountIdRoute,
  AuthedHouseholdPlanBucketsIdRoute: AuthedHouseholdPlanBucketsIdRoute,
  AuthedHouseholdPlanCommitmentsIdRoute: AuthedHouseholdPlanCommitmentsIdRoute,
  AuthedHouseholdPlanYearYearRoute: AuthedHouseholdPlanYearYearRoute,
}

const AuthedHouseholdRouteWithChildren = AuthedHouseholdRoute._addFileChildren(
  AuthedHouseholdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedHouseholdRoute: typeof AuthedHouseholdRouteWithChildren
  AuthedWelcomeRoute: typeof AuthedWelcomeRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHouseholdRoute: AuthedHouseholdRouteWithChildren,
  AuthedWelcomeRoute: AuthedWelcomeRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
