/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthedHouseholdRouteImport } from './routes/_authed/_household'
import { Route as AuthedJoinedRouteImport } from './routes/_authed/joined'
import { Route as AuthedSetupRouteImport } from './routes/_authed/setup'
import { Route as AuthedWelcomeRouteImport } from './routes/_authed/welcome'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AuthedHouseholdAccountsRouteImport } from './routes/_authed/_household/accounts'
import { Route as AuthedHouseholdAskRouteImport } from './routes/_authed/_household/ask'
import { Route as AuthedHouseholdCheckInRouteImport } from './routes/_authed/_household/check-in'
import { Route as AuthedHouseholdExploreRouteImport } from './routes/_authed/_household/explore'
import { Route as AuthedHouseholdGlossaryRouteImport } from './routes/_authed/_household/glossary'
import { Route as AuthedHouseholdGoalsRouteImport } from './routes/_authed/_household/goals'
import { Route as AuthedHouseholdHouseholdRouteImport } from './routes/_authed/_household/household'
import { Route as AuthedHouseholdInsightsRouteImport } from './routes/_authed/_household/insights'
import { Route as AuthedHouseholdPerksRouteImport } from './routes/_authed/_household/perks'
import { Route as AuthedHouseholdReportsRouteImport } from './routes/_authed/_household/reports'
import { Route as AuthedHouseholdReviewRouteImport } from './routes/_authed/_household/review'
import { Route as AuthedBankReturnRouteImport } from './routes/_authed/bank.return'
import { Route as AuthedHouseholdAccountsAccountIdRouteImport } from './routes/_authed/_household/accounts.$accountId'
import { Route as AuthedHouseholdExploreIndexRouteImport } from './routes/_authed/_household/explore.index'
import { Route as AuthedHouseholdExploreAffordRouteImport } from './routes/_authed/_household/explore.afford'
import { Route as AuthedHouseholdExploreScenariosRouteImport } from './routes/_authed/_household/explore.scenarios'
import { Route as AuthedHouseholdGoalsGoalIdRouteImport } from './routes/_authed/_household/goals.$goalId'
import { Route as AuthedHouseholdHouseholdIndexRouteImport } from './routes/_authed/_household/household.index'
import { Route as AuthedHouseholdHouseholdChangelogRouteImport } from './routes/_authed/_household/household.changelog'
import { Route as AuthedHouseholdHouseholdLogsRouteImport } from './routes/_authed/_household/household.logs'
import { Route as AuthedHouseholdInsightsIndexRouteImport } from './routes/_authed/_household/insights.index'
import { Route as AuthedHouseholdInsightsPerksRouteImport } from './routes/_authed/_household/insights.perks'
import { Route as AuthedHouseholdMonthIndexRouteImport } from './routes/_authed/_household/month.index'
import { Route as AuthedHouseholdMonthMonthRouteImport } from './routes/_authed/_household/month.$month'
import { Route as AuthedHouseholdPlanIndexRouteImport } from './routes/_authed/_household/plan.index'
import { Route as AuthedHouseholdPlanMonthRouteImport } from './routes/_authed/_household/plan.$month'
import { Route as AuthedHouseholdReviewIndexRouteImport } from './routes/_authed/_household/review.index'
import { Route as AuthedHouseholdReviewRulesRouteImport } from './routes/_authed/_household/review.rules'
import { Route as AuthedHouseholdTransactionsIndexRouteImport } from './routes/_authed/_household/transactions.index'
import { Route as AuthedHouseholdTransactionsMonthRouteImport } from './routes/_authed/_household/transactions.$month'
import { Route as AuthedHouseholdExploreScenariosIdRouteImport } from './routes/_authed/_household/explore.scenarios.$id'
import { Route as AuthedHouseholdGoalsAccountsAccountIdRouteImport } from './routes/_authed/_household/goals_.accounts.$accountId'
import { Route as AuthedHouseholdMonthMonthIndexRouteImport } from './routes/_authed/_household/month.$month.index'
import { Route as AuthedHouseholdMonthMonthPlanRouteImport } from './routes/_authed/_household/month.$month.plan'
import { Route as AuthedHouseholdPlanMonthHomeRouteImport } from './routes/_authed/_household/plan.$month._home'
import { Route as AuthedHouseholdPlanMonthCommitmentsRouteImport } from './routes/_authed/_household/plan.$month.commitments'
import { Route as AuthedHouseholdPlanMonthGoalsRouteImport } from './routes/_authed/_household/plan.$month.goals'
import { Route as AuthedHouseholdPlanMonthIncomeRouteImport } from './routes/_authed/_household/plan.$month.income'
import { Route as AuthedHouseholdPlanMonthYearRouteImport } from './routes/_authed/_household/plan.$month.year'
import { Route as AuthedHouseholdPlanBucketsIdRouteImport } from './routes/_authed/_household/plan.buckets.$id'
import { Route as AuthedHouseholdPlanCommitmentsIdRouteImport } from './routes/_authed/_household/plan.commitments.$id'
import { Route as AuthedHouseholdPlanYearYearRouteImport } from './routes/_authed/_household/plan.year.$year'
import { Route as AuthedHouseholdReviewRulesRuleIdRouteImport } from './routes/_authed/_household/review.rules.$ruleId'
import { Route as AuthedHouseholdTransactionsMonthTransactionIdRouteImport } from './routes/_authed/_household/transactions.$month.$transactionId'
import { Route as AuthedHouseholdPlanMonthHomeIndexRouteImport } from './routes/_authed/_household/plan.$month._home.index'
import { Route as AuthedHouseholdPlanMonthCommitmentsIdRouteImport } from './routes/_authed/_household/plan.$month.commitments.$id'
import { Route as AuthedHouseholdPlanMonthHomeBucketsIndexRouteImport } from './routes/_authed/_household/plan.$month._home.buckets.index'
import { Route as AuthedHouseholdPlanMonthHomeBucketsIdRouteImport } from './routes/_authed/_household/plan.$month._home.buckets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHouseholdRoute = AuthedHouseholdRouteImport.update({
  id: '/_household',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJoinedRoute = AuthedJoinedRouteImport.update({
  id: '/joined',
  path: '/joined',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSetupRoute = AuthedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWelcomeRoute = AuthedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthedRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHouseholdAccountsRoute = AuthedHouseholdAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdAskRoute = AuthedHouseholdAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdCheckInRoute = AuthedHouseholdCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdExploreRoute = AuthedHouseholdExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdGlossaryRoute = AuthedHouseholdGlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdGoalsRoute = AuthedHouseholdGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdHouseholdRoute =
  AuthedHouseholdHouseholdRouteImport.update({
    id: '/household',
    path: '/household',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdInsightsRoute = AuthedHouseholdInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdPerksRoute = AuthedHouseholdPerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdReportsRoute = AuthedHouseholdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedHouseholdReviewRoute = AuthedHouseholdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthedHouseholdRoute,
} as any)
const AuthedBankReturnRoute = AuthedBankReturnRouteImport.update({
  id: '/bank/return',
  path: '/bank/return',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHouseholdAccountsAccountIdRoute =
  AuthedHouseholdAccountsAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AuthedHouseholdAccountsRoute,
  } as any)
const AuthedHouseholdExploreIndexRoute =
  AuthedHouseholdExploreIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedHouseholdExploreRoute,
  } as any)
const AuthedHouseholdExploreAffordRoute =
  AuthedHouseholdExploreAffordRouteImport.update({
    id: '/afford',
    path: '/afford',
    getParentRoute: () => AuthedHouseholdExploreRoute,
  } as any)
const AuthedHouseholdExploreScenariosRoute =
  AuthedHouseholdExploreScenariosRouteImport.update({
    id: '/scenarios',
    path: '/scenarios',
    getParentRoute: () => AuthedHouseholdExploreRoute,
  } as any)
const AuthedHouseholdGoalsGoalIdRoute =
  AuthedHouseholdGoalsGoalIdRouteImport.update({
    id: '/$goalId',
    path: '/$goalId',
    getParentRoute: () => AuthedHouseholdGoalsRoute,
  } as any)
const AuthedHouseholdHouseholdIndexRoute =
  AuthedHouseholdHouseholdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedHouseholdHouseholdRoute,
  } as any)
const AuthedHouseholdHouseholdChangelogRoute =
  AuthedHouseholdHouseholdChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => AuthedHouseholdHouseholdRoute,
  } as any)
const AuthedHouseholdHouseholdLogsRoute =
  AuthedHouseholdHouseholdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthedHouseholdHouseholdRoute,
  } as any)
const AuthedHouseholdInsightsIndexRoute =
  AuthedHouseholdInsightsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedHouseholdInsightsRoute,
  } as any)
const AuthedHouseholdInsightsPerksRoute =
  AuthedHouseholdInsightsPerksRouteImport.update({
    id: '/perks',
    path: '/perks',
    getParentRoute: () => AuthedHouseholdInsightsRoute,
  } as any)
const AuthedHouseholdMonthIndexRoute =
  AuthedHouseholdMonthIndexRouteImport.update({
    id: '/month/',
    path: '/month/',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdMonthMonthRoute =
  AuthedHouseholdMonthMonthRouteImport.update({
    id: '/month/$month',
    path: '/month/$month',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdPlanIndexRoute =
  AuthedHouseholdPlanIndexRouteImport.update({
    id: '/plan/',
    path: '/plan/',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdPlanMonthRoute =
  AuthedHouseholdPlanMonthRouteImport.update({
    id: '/plan/$month',
    path: '/plan/$month',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdReviewIndexRoute =
  AuthedHouseholdReviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedHouseholdReviewRoute,
  } as any)
const AuthedHouseholdReviewRulesRoute =
  AuthedHouseholdReviewRulesRouteImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => AuthedHouseholdReviewRoute,
  } as any)
const AuthedHouseholdTransactionsIndexRoute =
  AuthedHouseholdTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdTransactionsMonthRoute =
  AuthedHouseholdTransactionsMonthRouteImport.update({
    id: '/transactions/$month',
    path: '/transactions/$month',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdExploreScenariosIdRoute =
  AuthedHouseholdExploreScenariosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthedHouseholdExploreScenariosRoute,
  } as any)
const AuthedHouseholdGoalsAccountsAccountIdRoute =
  AuthedHouseholdGoalsAccountsAccountIdRouteImport.update({
    id: '/goals_/accounts/$accountId',
    path: '/goals/accounts/$accountId',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdMonthMonthIndexRoute =
  AuthedHouseholdMonthMonthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedHouseholdMonthMonthRoute,
  } as any)
const AuthedHouseholdMonthMonthPlanRoute =
  AuthedHouseholdMonthMonthPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AuthedHouseholdMonthMonthRoute,
  } as any)
const AuthedHouseholdPlanMonthHomeRoute =
  AuthedHouseholdPlanMonthHomeRouteImport.update({
    id: '/_home',
    getParentRoute: () => AuthedHouseholdPlanMonthRoute,
  } as any)
const AuthedHouseholdPlanMonthCommitmentsRoute =
  AuthedHouseholdPlanMonthCommitmentsRouteImport.update({
    id: '/commitments',
    path: '/commitments',
    getParentRoute: () => AuthedHouseholdPlanMonthRoute,
  } as any)
const AuthedHouseholdPlanMonthGoalsRoute =
  AuthedHouseholdPlanMonthGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => AuthedHouseholdPlanMonthRoute,
  } as any)
const AuthedHouseholdPlanMonthIncomeRoute =
  AuthedHouseholdPlanMonthIncomeRouteImport.update({
    id: '/income',
    path: '/income',
    getParentRoute: () => AuthedHouseholdPlanMonthRoute,
  } as any)
const AuthedHouseholdPlanMonthYearRoute =
  AuthedHouseholdPlanMonthYearRouteImport.update({
    id: '/year',
    path: '/year',
    getParentRoute: () => AuthedHouseholdPlanMonthRoute,
  } as any)
const AuthedHouseholdPlanBucketsIdRoute =
  AuthedHouseholdPlanBucketsIdRouteImport.update({
    id: '/plan/buckets/$id',
    path: '/plan/buckets/$id',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdPlanCommitmentsIdRoute =
  AuthedHouseholdPlanCommitmentsIdRouteImport.update({
    id: '/plan/commitments/$id',
    path: '/plan/commitments/$id',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdPlanYearYearRoute =
  AuthedHouseholdPlanYearYearRouteImport.update({
    id: '/plan/year/$year',
    path: '/plan/year/$year',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdReviewRulesRuleIdRoute =
  AuthedHouseholdReviewRulesRuleIdRouteImport.update({
    id: '/$ruleId',
    path: '/$ruleId',
    getParentRoute: () => AuthedHouseholdReviewRulesRoute,
  } as any)
const AuthedHouseholdTransactionsMonthTransactionIdRoute =
  AuthedHouseholdTransactionsMonthTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => AuthedHouseholdTransactionsMonthRoute,
  } as any)
const AuthedHouseholdPlanMonthHomeIndexRoute =
  AuthedHouseholdPlanMonthHomeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedHouseholdPlanMonthHomeRoute,
  } as any)
const AuthedHouseholdPlanMonthCommitmentsIdRoute =
  AuthedHouseholdPlanMonthCommitmentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthedHouseholdPlanMonthCommitmentsRoute,
  } as any)
const AuthedHouseholdPlanMonthHomeBucketsIndexRoute =
  AuthedHouseholdPlanMonthHomeBucketsIndexRouteImport.update({
    id: '/buckets/',
    path: '/buckets/',
    getParentRoute: () => AuthedHouseholdPlanMonthHomeRoute,
  } as any)
const AuthedHouseholdPlanMonthHomeBucketsIdRoute =
  AuthedHouseholdPlanMonthHomeBucketsIdRouteImport.update({
    id: '/buckets/$id',
    path: '/buckets/$id',
    getParentRoute: () => AuthedHouseholdPlanMonthHomeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/joined': typeof AuthedJoinedRoute
  '/setup': typeof AuthedSetupRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/accounts': typeof AuthedHouseholdAccountsRouteWithChildren
  '/ask': typeof AuthedHouseholdAskRoute
  '/check-in': typeof AuthedHouseholdCheckInRoute
  '/explore': typeof AuthedHouseholdExploreRouteWithChildren
  '/glossary': typeof AuthedHouseholdGlossaryRoute
  '/goals': typeof AuthedHouseholdGoalsRouteWithChildren
  '/household': typeof AuthedHouseholdHouseholdRouteWithChildren
  '/insights': typeof AuthedHouseholdInsightsRouteWithChildren
  '/perks': typeof AuthedHouseholdPerksRoute
  '/reports': typeof AuthedHouseholdReportsRoute
  '/review': typeof AuthedHouseholdReviewRouteWithChildren
  '/bank/return': typeof AuthedBankReturnRoute
  '/accounts/$accountId': typeof AuthedHouseholdAccountsAccountIdRoute
  '/explore/afford': typeof AuthedHouseholdExploreAffordRoute
  '/explore/scenarios': typeof AuthedHouseholdExploreScenariosRouteWithChildren
  '/goals/$goalId': typeof AuthedHouseholdGoalsGoalIdRoute
  '/household/changelog': typeof AuthedHouseholdHouseholdChangelogRoute
  '/household/logs': typeof AuthedHouseholdHouseholdLogsRoute
  '/insights/perks': typeof AuthedHouseholdInsightsPerksRoute
  '/month/$month': typeof AuthedHouseholdMonthMonthRouteWithChildren
  '/plan/$month': typeof AuthedHouseholdPlanMonthRouteWithChildren
  '/review/rules': typeof AuthedHouseholdReviewRulesRouteWithChildren
  '/transactions/$month': typeof AuthedHouseholdTransactionsMonthRouteWithChildren
  '/explore/': typeof AuthedHouseholdExploreIndexRoute
  '/household/': typeof AuthedHouseholdHouseholdIndexRoute
  '/insights/': typeof AuthedHouseholdInsightsIndexRoute
  '/month/': typeof AuthedHouseholdMonthIndexRoute
  '/plan/': typeof AuthedHouseholdPlanIndexRoute
  '/review/': typeof AuthedHouseholdReviewIndexRoute
  '/transactions/': typeof AuthedHouseholdTransactionsIndexRoute
  '/explore/scenarios/$id': typeof AuthedHouseholdExploreScenariosIdRoute
  '/goals/accounts/$accountId': typeof AuthedHouseholdGoalsAccountsAccountIdRoute
  '/month/$month/plan': typeof AuthedHouseholdMonthMonthPlanRoute
  '/plan/$month/commitments': typeof AuthedHouseholdPlanMonthCommitmentsRouteWithChildren
  '/plan/$month/goals': typeof AuthedHouseholdPlanMonthGoalsRoute
  '/plan/$month/income': typeof AuthedHouseholdPlanMonthIncomeRoute
  '/plan/$month/year': typeof AuthedHouseholdPlanMonthYearRoute
  '/plan/buckets/$id': typeof AuthedHouseholdPlanBucketsIdRoute
  '/plan/commitments/$id': typeof AuthedHouseholdPlanCommitmentsIdRoute
  '/plan/year/$year': typeof AuthedHouseholdPlanYearYearRoute
  '/review/rules/$ruleId': typeof AuthedHouseholdReviewRulesRuleIdRoute
  '/transactions/$month/$transactionId': typeof AuthedHouseholdTransactionsMonthTransactionIdRoute
  '/month/$month/': typeof AuthedHouseholdMonthMonthIndexRoute
  '/plan/$month/commitments/$id': typeof AuthedHouseholdPlanMonthCommitmentsIdRoute
  '/plan/$month/': typeof AuthedHouseholdPlanMonthHomeIndexRoute
  '/plan/$month/buckets/$id': typeof AuthedHouseholdPlanMonthHomeBucketsIdRoute
  '/plan/$month/buckets/': typeof AuthedHouseholdPlanMonthHomeBucketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/joined': typeof AuthedJoinedRoute
  '/setup': typeof AuthedSetupRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/docs': typeof DocsIndexRoute
  '/accounts': typeof AuthedHouseholdAccountsRouteWithChildren
  '/ask': typeof AuthedHouseholdAskRoute
  '/check-in': typeof AuthedHouseholdCheckInRoute
  '/glossary': typeof AuthedHouseholdGlossaryRoute
  '/goals': typeof AuthedHouseholdGoalsRouteWithChildren
  '/perks': typeof AuthedHouseholdPerksRoute
  '/reports': typeof AuthedHouseholdReportsRoute
  '/bank/return': typeof AuthedBankReturnRoute
  '/accounts/$accountId': typeof AuthedHouseholdAccountsAccountIdRoute
  '/explore/afford': typeof AuthedHouseholdExploreAffordRoute
  '/explore/scenarios': typeof AuthedHouseholdExploreScenariosRouteWithChildren
  '/goals/$goalId': typeof AuthedHouseholdGoalsGoalIdRoute
  '/household/changelog': typeof AuthedHouseholdHouseholdChangelogRoute
  '/household/logs': typeof AuthedHouseholdHouseholdLogsRoute
  '/insights/perks': typeof AuthedHouseholdInsightsPerksRoute
  '/plan/$month': typeof AuthedHouseholdPlanMonthHomeIndexRoute
  '/review/rules': typeof AuthedHouseholdReviewRulesRouteWithChildren
  '/transactions/$month': typeof AuthedHouseholdTransactionsMonthRouteWithChildren
  '/explore': typeof AuthedHouseholdExploreIndexRoute
  '/household': typeof AuthedHouseholdHouseholdIndexRoute
  '/insights': typeof AuthedHouseholdInsightsIndexRoute
  '/month': typeof AuthedHouseholdMonthIndexRoute
  '/plan': typeof AuthedHouseholdPlanIndexRoute
  '/review': typeof AuthedHouseholdReviewIndexRoute
  '/transactions': typeof AuthedHouseholdTransactionsIndexRoute
  '/explore/scenarios/$id': typeof AuthedHouseholdExploreScenariosIdRoute
  '/goals/accounts/$accountId': typeof AuthedHouseholdGoalsAccountsAccountIdRoute
  '/month/$month/plan': typeof AuthedHouseholdMonthMonthPlanRoute
  '/plan/$month/commitments': typeof AuthedHouseholdPlanMonthCommitmentsRouteWithChildren
  '/plan/$month/goals': typeof AuthedHouseholdPlanMonthGoalsRoute
  '/plan/$month/income': typeof AuthedHouseholdPlanMonthIncomeRoute
  '/plan/$month/year': typeof AuthedHouseholdPlanMonthYearRoute
  '/plan/buckets/$id': typeof AuthedHouseholdPlanBucketsIdRoute
  '/plan/commitments/$id': typeof AuthedHouseholdPlanCommitmentsIdRoute
  '/plan/year/$year': typeof AuthedHouseholdPlanYearYearRoute
  '/review/rules/$ruleId': typeof AuthedHouseholdReviewRulesRuleIdRoute
  '/transactions/$month/$transactionId': typeof AuthedHouseholdTransactionsMonthTransactionIdRoute
  '/month/$month': typeof AuthedHouseholdMonthMonthIndexRoute
  '/plan/$month/commitments/$id': typeof AuthedHouseholdPlanMonthCommitmentsIdRoute
  '/plan/$month/buckets/$id': typeof AuthedHouseholdPlanMonthHomeBucketsIdRoute
  '/plan/$month/buckets': typeof AuthedHouseholdPlanMonthHomeBucketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/_authed/_household': typeof AuthedHouseholdRouteWithChildren
  '/_authed/joined': typeof AuthedJoinedRoute
  '/_authed/setup': typeof AuthedSetupRoute
  '/_authed/welcome': typeof AuthedWelcomeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/_authed/_household/accounts': typeof AuthedHouseholdAccountsRouteWithChildren
  '/_authed/_household/ask': typeof AuthedHouseholdAskRoute
  '/_authed/_household/check-in': typeof AuthedHouseholdCheckInRoute
  '/_authed/_household/explore': typeof AuthedHouseholdExploreRouteWithChildren
  '/_authed/_household/glossary': typeof AuthedHouseholdGlossaryRoute
  '/_authed/_household/goals': typeof AuthedHouseholdGoalsRouteWithChildren
  '/_authed/_household/household': typeof AuthedHouseholdHouseholdRouteWithChildren
  '/_authed/_household/insights': typeof AuthedHouseholdInsightsRouteWithChildren
  '/_authed/_household/perks': typeof AuthedHouseholdPerksRoute
  '/_authed/_household/reports': typeof AuthedHouseholdReportsRoute
  '/_authed/_household/review': typeof AuthedHouseholdReviewRouteWithChildren
  '/_authed/bank/return': typeof AuthedBankReturnRoute
  '/_authed/_household/accounts/$accountId': typeof AuthedHouseholdAccountsAccountIdRoute
  '/_authed/_household/explore/afford': typeof AuthedHouseholdExploreAffordRoute
  '/_authed/_household/explore/scenarios': typeof AuthedHouseholdExploreScenariosRouteWithChildren
  '/_authed/_household/goals/$goalId': typeof AuthedHouseholdGoalsGoalIdRoute
  '/_authed/_household/household/changelog': typeof AuthedHouseholdHouseholdChangelogRoute
  '/_authed/_household/household/logs': typeof AuthedHouseholdHouseholdLogsRoute
  '/_authed/_household/insights/perks': typeof AuthedHouseholdInsightsPerksRoute
  '/_authed/_household/month/$month': typeof AuthedHouseholdMonthMonthRouteWithChildren
  '/_authed/_household/plan/$month': typeof AuthedHouseholdPlanMonthRouteWithChildren
  '/_authed/_household/review/rules': typeof AuthedHouseholdReviewRulesRouteWithChildren
  '/_authed/_household/transactions/$month': typeof AuthedHouseholdTransactionsMonthRouteWithChildren
  '/_authed/_household/explore/': typeof AuthedHouseholdExploreIndexRoute
  '/_authed/_household/household/': typeof AuthedHouseholdHouseholdIndexRoute
  '/_authed/_household/insights/': typeof AuthedHouseholdInsightsIndexRoute
  '/_authed/_household/month/': typeof AuthedHouseholdMonthIndexRoute
  '/_authed/_household/plan/': typeof AuthedHouseholdPlanIndexRoute
  '/_authed/_household/review/': typeof AuthedHouseholdReviewIndexRoute
  '/_authed/_household/transactions/': typeof AuthedHouseholdTransactionsIndexRoute
  '/_authed/_household/explore/scenarios/$id': typeof AuthedHouseholdExploreScenariosIdRoute
  '/_authed/_household/goals_/accounts/$accountId': typeof AuthedHouseholdGoalsAccountsAccountIdRoute
  '/_authed/_household/month/$month/plan': typeof AuthedHouseholdMonthMonthPlanRoute
  '/_authed/_household/plan/$month/_home': typeof AuthedHouseholdPlanMonthHomeRouteWithChildren
  '/_authed/_household/plan/$month/commitments': typeof AuthedHouseholdPlanMonthCommitmentsRouteWithChildren
  '/_authed/_household/plan/$month/goals': typeof AuthedHouseholdPlanMonthGoalsRoute
  '/_authed/_household/plan/$month/income': typeof AuthedHouseholdPlanMonthIncomeRoute
  '/_authed/_household/plan/$month/year': typeof AuthedHouseholdPlanMonthYearRoute
  '/_authed/_household/plan/buckets/$id': typeof AuthedHouseholdPlanBucketsIdRoute
  '/_authed/_household/plan/commitments/$id': typeof AuthedHouseholdPlanCommitmentsIdRoute
  '/_authed/_household/plan/year/$year': typeof AuthedHouseholdPlanYearYearRoute
  '/_authed/_household/review/rules/$ruleId': typeof AuthedHouseholdReviewRulesRuleIdRoute
  '/_authed/_household/transactions/$month/$transactionId': typeof AuthedHouseholdTransactionsMonthTransactionIdRoute
  '/_authed/_household/month/$month/': typeof AuthedHouseholdMonthMonthIndexRoute
  '/_authed/_household/plan/$month/commitments/$id': typeof AuthedHouseholdPlanMonthCommitmentsIdRoute
  '/_authed/_household/plan/$month/_home/': typeof AuthedHouseholdPlanMonthHomeIndexRoute
  '/_authed/_household/plan/$month/_home/buckets/$id': typeof AuthedHouseholdPlanMonthHomeBucketsIdRoute
  '/_authed/_household/plan/$month/_home/buckets/': typeof AuthedHouseholdPlanMonthHomeBucketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/joined'
    | '/setup'
    | '/welcome'
    | '/docs/$slug'
    | '/invite/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/docs/'
    | '/accounts'
    | '/ask'
    | '/check-in'
    | '/explore'
    | '/glossary'
    | '/goals'
    | '/household'
    | '/insights'
    | '/perks'
    | '/reports'
    | '/review'
    | '/bank/return'
    | '/accounts/$accountId'
    | '/explore/afford'
    | '/explore/scenarios'
    | '/goals/$goalId'
    | '/household/changelog'
    | '/household/logs'
    | '/insights/perks'
    | '/month/$month'
    | '/plan/$month'
    | '/review/rules'
    | '/transactions/$month'
    | '/explore/'
    | '/household/'
    | '/insights/'
    | '/month/'
    | '/plan/'
    | '/review/'
    | '/transactions/'
    | '/explore/scenarios/$id'
    | '/goals/accounts/$accountId'
    | '/month/$month/plan'
    | '/plan/$month/commitments'
    | '/plan/$month/goals'
    | '/plan/$month/income'
    | '/plan/$month/year'
    | '/plan/buckets/$id'
    | '/plan/commitments/$id'
    | '/plan/year/$year'
    | '/review/rules/$ruleId'
    | '/transactions/$month/$transactionId'
    | '/month/$month/'
    | '/plan/$month/commitments/$id'
    | '/plan/$month/'
    | '/plan/$month/buckets/$id'
    | '/plan/$month/buckets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/joined'
    | '/setup'
    | '/welcome'
    | '/docs/$slug'
    | '/invite/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/docs'
    | '/accounts'
    | '/ask'
    | '/check-in'
    | '/glossary'
    | '/goals'
    | '/perks'
    | '/reports'
    | '/bank/return'
    | '/accounts/$accountId'
    | '/explore/afford'
    | '/explore/scenarios'
    | '/goals/$goalId'
    | '/household/changelog'
    | '/household/logs'
    | '/insights/perks'
    | '/plan/$month'
    | '/review/rules'
    | '/transactions/$month'
    | '/explore'
    | '/household'
    | '/insights'
    | '/month'
    | '/plan'
    | '/review'
    | '/transactions'
    | '/explore/scenarios/$id'
    | '/goals/accounts/$accountId'
    | '/month/$month/plan'
    | '/plan/$month/commitments'
    | '/plan/$month/goals'
    | '/plan/$month/income'
    | '/plan/$month/year'
    | '/plan/buckets/$id'
    | '/plan/commitments/$id'
    | '/plan/year/$year'
    | '/review/rules/$ruleId'
    | '/transactions/$month/$transactionId'
    | '/month/$month'
    | '/plan/$month/commitments/$id'
    | '/plan/$month/buckets/$id'
    | '/plan/$month/buckets'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/docs'
    | '/_authed/_household'
    | '/_authed/joined'
    | '/_authed/setup'
    | '/_authed/welcome'
    | '/docs/$slug'
    | '/invite/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/docs/'
    | '/_authed/_household/accounts'
    | '/_authed/_household/ask'
    | '/_authed/_household/check-in'
    | '/_authed/_household/explore'
    | '/_authed/_household/glossary'
    | '/_authed/_household/goals'
    | '/_authed/_household/household'
    | '/_authed/_household/insights'
    | '/_authed/_household/perks'
    | '/_authed/_household/reports'
    | '/_authed/_household/review'
    | '/_authed/bank/return'
    | '/_authed/_household/accounts/$accountId'
    | '/_authed/_household/explore/afford'
    | '/_authed/_household/explore/scenarios'
    | '/_authed/_household/goals/$goalId'
    | '/_authed/_household/household/changelog'
    | '/_authed/_household/household/logs'
    | '/_authed/_household/insights/perks'
    | '/_authed/_household/month/$month'
    | '/_authed/_household/plan/$month'
    | '/_authed/_household/review/rules'
    | '/_authed/_household/transactions/$month'
    | '/_authed/_household/explore/'
    | '/_authed/_household/household/'
    | '/_authed/_household/insights/'
    | '/_authed/_household/month/'
    | '/_authed/_household/plan/'
    | '/_authed/_household/review/'
    | '/_authed/_household/transactions/'
    | '/_authed/_household/explore/scenarios/$id'
    | '/_authed/_household/goals_/accounts/$accountId'
    | '/_authed/_household/month/$month/plan'
    | '/_authed/_household/plan/$month/_home'
    | '/_authed/_household/plan/$month/commitments'
    | '/_authed/_household/plan/$month/goals'
    | '/_authed/_household/plan/$month/income'
    | '/_authed/_household/plan/$month/year'
    | '/_authed/_household/plan/buckets/$id'
    | '/_authed/_household/plan/commitments/$id'
    | '/_authed/_household/plan/year/$year'
    | '/_authed/_household/review/rules/$ruleId'
    | '/_authed/_household/transactions/$month/$transactionId'
    | '/_authed/_household/month/$month/'
    | '/_authed/_household/plan/$month/commitments/$id'
    | '/_authed/_household/plan/$month/_home/'
    | '/_authed/_household/plan/$month/_home/buckets/$id'
    | '/_authed/_household/plan/$month/_home/buckets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_household': {
      id: '/_authed/_household'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedHouseholdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/joined': {
      id: '/_authed/joined'
      path: '/joined'
      fullPath: '/joined'
      preLoaderRoute: typeof AuthedJoinedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/setup': {
      id: '/_authed/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthedSetupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/welcome': {
      id: '/_authed/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthedWelcomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_household/accounts': {
      id: '/_authed/_household/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthedHouseholdAccountsRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/ask': {
      id: '/_authed/_household/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthedHouseholdAskRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/check-in': {
      id: '/_authed/_household/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthedHouseholdCheckInRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/explore': {
      id: '/_authed/_household/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthedHouseholdExploreRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/glossary': {
      id: '/_authed/_household/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof AuthedHouseholdGlossaryRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/goals': {
      id: '/_authed/_household/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthedHouseholdGoalsRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/household': {
      id: '/_authed/_household/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AuthedHouseholdHouseholdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/insights': {
      id: '/_authed/_household/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthedHouseholdInsightsRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/perks': {
      id: '/_authed/_household/perks'
      path: '/perks'
      fullPath: '/perks'
      preLoaderRoute: typeof AuthedHouseholdPerksRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/reports': {
      id: '/_authed/_household/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedHouseholdReportsRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/review': {
      id: '/_authed/_household/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthedHouseholdReviewRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/bank/return': {
      id: '/_authed/bank/return'
      path: '/bank/return'
      fullPath: '/bank/return'
      preLoaderRoute: typeof AuthedBankReturnRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_household/accounts/$accountId': {
      id: '/_authed/_household/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthedHouseholdAccountsAccountIdRouteImport
      parentRoute: typeof AuthedHouseholdAccountsRoute
    }
    '/_authed/_household/explore/': {
      id: '/_authed/_household/explore/'
      path: '/'
      fullPath: '/explore/'
      preLoaderRoute: typeof AuthedHouseholdExploreIndexRouteImport
      parentRoute: typeof AuthedHouseholdExploreRoute
    }
    '/_authed/_household/explore/afford': {
      id: '/_authed/_household/explore/afford'
      path: '/afford'
      fullPath: '/explore/afford'
      preLoaderRoute: typeof AuthedHouseholdExploreAffordRouteImport
      parentRoute: typeof AuthedHouseholdExploreRoute
    }
    '/_authed/_household/explore/scenarios': {
      id: '/_authed/_household/explore/scenarios'
      path: '/scenarios'
      fullPath: '/explore/scenarios'
      preLoaderRoute: typeof AuthedHouseholdExploreScenariosRouteImport
      parentRoute: typeof AuthedHouseholdExploreRoute
    }
    '/_authed/_household/goals/$goalId': {
      id: '/_authed/_household/goals/$goalId'
      path: '/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof AuthedHouseholdGoalsGoalIdRouteImport
      parentRoute: typeof AuthedHouseholdGoalsRoute
    }
    '/_authed/_household/household/': {
      id: '/_authed/_household/household/'
      path: '/'
      fullPath: '/household/'
      preLoaderRoute: typeof AuthedHouseholdHouseholdIndexRouteImport
      parentRoute: typeof AuthedHouseholdHouseholdRoute
    }
    '/_authed/_household/household/changelog': {
      id: '/_authed/_household/household/changelog'
      path: '/changelog'
      fullPath: '/household/changelog'
      preLoaderRoute: typeof AuthedHouseholdHouseholdChangelogRouteImport
      parentRoute: typeof AuthedHouseholdHouseholdRoute
    }
    '/_authed/_household/household/logs': {
      id: '/_authed/_household/household/logs'
      path: '/logs'
      fullPath: '/household/logs'
      preLoaderRoute: typeof AuthedHouseholdHouseholdLogsRouteImport
      parentRoute: typeof AuthedHouseholdHouseholdRoute
    }
    '/_authed/_household/insights/': {
      id: '/_authed/_household/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof AuthedHouseholdInsightsIndexRouteImport
      parentRoute: typeof AuthedHouseholdInsightsRoute
    }
    '/_authed/_household/insights/perks': {
      id: '/_authed/_household/insights/perks'
      path: '/perks'
      fullPath: '/insights/perks'
      preLoaderRoute: typeof AuthedHouseholdInsightsPerksRouteImport
      parentRoute: typeof AuthedHouseholdInsightsRoute
    }
    '/_authed/_household/month/': {
      id: '/_authed/_household/month/'
      path: '/month'
      fullPath: '/month/'
      preLoaderRoute: typeof AuthedHouseholdMonthIndexRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/month/$month': {
      id: '/_authed/_household/month/$month'
      path: '/month/$month'
      fullPath: '/month/$month'
      preLoaderRoute: typeof AuthedHouseholdMonthMonthRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/plan/': {
      id: '/_authed/_household/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof AuthedHouseholdPlanIndexRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/plan/$month': {
      id: '/_authed/_household/plan/$month'
      path: '/plan/$month'
      fullPath: '/plan/$month'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/review/': {
      id: '/_authed/_household/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof AuthedHouseholdReviewIndexRouteImport
      parentRoute: typeof AuthedHouseholdReviewRoute
    }
    '/_authed/_household/review/rules': {
      id: '/_authed/_household/review/rules'
      path: '/rules'
      fullPath: '/review/rules'
      preLoaderRoute: typeof AuthedHouseholdReviewRulesRouteImport
      parentRoute: typeof AuthedHouseholdReviewRoute
    }
    '/_authed/_household/transactions/': {
      id: '/_authed/_household/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthedHouseholdTransactionsIndexRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/transactions/$month': {
      id: '/_authed/_household/transactions/$month'
      path: '/transactions/$month'
      fullPath: '/transactions/$month'
      preLoaderRoute: typeof AuthedHouseholdTransactionsMonthRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/explore/scenarios/$id': {
      id: '/_authed/_household/explore/scenarios/$id'
      path: '/$id'
      fullPath: '/explore/scenarios/$id'
      preLoaderRoute: typeof AuthedHouseholdExploreScenariosIdRouteImport
      parentRoute: typeof AuthedHouseholdExploreScenariosRoute
    }
    '/_authed/_household/goals_/accounts/$accountId': {
      id: '/_authed/_household/goals_/accounts/$accountId'
      path: '/goals/accounts/$accountId'
      fullPath: '/goals/accounts/$accountId'
      preLoaderRoute: typeof AuthedHouseholdGoalsAccountsAccountIdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/month/$month/': {
      id: '/_authed/_household/month/$month/'
      path: '/'
      fullPath: '/month/$month/'
      preLoaderRoute: typeof AuthedHouseholdMonthMonthIndexRouteImport
      parentRoute: typeof AuthedHouseholdMonthMonthRoute
    }
    '/_authed/_household/month/$month/plan': {
      id: '/_authed/_household/month/$month/plan'
      path: '/plan'
      fullPath: '/month/$month/plan'
      preLoaderRoute: typeof AuthedHouseholdMonthMonthPlanRouteImport
      parentRoute: typeof AuthedHouseholdMonthMonthRoute
    }
    '/_authed/_household/plan/$month/_home': {
      id: '/_authed/_household/plan/$month/_home'
      path: ''
      fullPath: '/plan/$month'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthHomeRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthRoute
    }
    '/_authed/_household/plan/$month/commitments': {
      id: '/_authed/_household/plan/$month/commitments'
      path: '/commitments'
      fullPath: '/plan/$month/commitments'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthCommitmentsRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthRoute
    }
    '/_authed/_household/plan/$month/goals': {
      id: '/_authed/_household/plan/$month/goals'
      path: '/goals'
      fullPath: '/plan/$month/goals'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthGoalsRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthRoute
    }
    '/_authed/_household/plan/$month/income': {
      id: '/_authed/_household/plan/$month/income'
      path: '/income'
      fullPath: '/plan/$month/income'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthIncomeRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthRoute
    }
    '/_authed/_household/plan/$month/year': {
      id: '/_authed/_household/plan/$month/year'
      path: '/year'
      fullPath: '/plan/$month/year'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthYearRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthRoute
    }
    '/_authed/_household/plan/buckets/$id': {
      id: '/_authed/_household/plan/buckets/$id'
      path: '/plan/buckets/$id'
      fullPath: '/plan/buckets/$id'
      preLoaderRoute: typeof AuthedHouseholdPlanBucketsIdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/plan/commitments/$id': {
      id: '/_authed/_household/plan/commitments/$id'
      path: '/plan/commitments/$id'
      fullPath: '/plan/commitments/$id'
      preLoaderRoute: typeof AuthedHouseholdPlanCommitmentsIdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/plan/year/$year': {
      id: '/_authed/_household/plan/year/$year'
      path: '/plan/year/$year'
      fullPath: '/plan/year/$year'
      preLoaderRoute: typeof AuthedHouseholdPlanYearYearRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/review/rules/$ruleId': {
      id: '/_authed/_household/review/rules/$ruleId'
      path: '/$ruleId'
      fullPath: '/review/rules/$ruleId'
      preLoaderRoute: typeof AuthedHouseholdReviewRulesRuleIdRouteImport
      parentRoute: typeof AuthedHouseholdReviewRulesRoute
    }
    '/_authed/_household/transactions/$month/$transactionId': {
      id: '/_authed/_household/transactions/$month/$transactionId'
      path: '/$transactionId'
      fullPath: '/transactions/$month/$transactionId'
      preLoaderRoute: typeof AuthedHouseholdTransactionsMonthTransactionIdRouteImport
      parentRoute: typeof AuthedHouseholdTransactionsMonthRoute
    }
    '/_authed/_household/plan/$month/_home/': {
      id: '/_authed/_household/plan/$month/_home/'
      path: '/'
      fullPath: '/plan/$month/'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthHomeIndexRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthHomeRoute
    }
    '/_authed/_household/plan/$month/commitments/$id': {
      id: '/_authed/_household/plan/$month/commitments/$id'
      path: '/$id'
      fullPath: '/plan/$month/commitments/$id'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthCommitmentsIdRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthCommitmentsRoute
    }
    '/_authed/_household/plan/$month/_home/buckets/': {
      id: '/_authed/_household/plan/$month/_home/buckets/'
      path: '/buckets'
      fullPath: '/plan/$month/buckets/'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthHomeBucketsIndexRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthHomeRoute
    }
    '/_authed/_household/plan/$month/_home/buckets/$id': {
      id: '/_authed/_household/plan/$month/_home/buckets/$id'
      path: '/buckets/$id'
      fullPath: '/plan/$month/buckets/$id'
      preLoaderRoute: typeof AuthedHouseholdPlanMonthHomeBucketsIdRouteImport
      parentRoute: typeof AuthedHouseholdPlanMonthHomeRoute
    }
  }
}

interface AuthedHouseholdAccountsRouteChildren {
  AuthedHouseholdAccountsAccountIdRoute: typeof AuthedHouseholdAccountsAccountIdRoute
}

const AuthedHouseholdAccountsRouteChildren: AuthedHouseholdAccountsRouteChildren =
  {
    AuthedHouseholdAccountsAccountIdRoute:
      AuthedHouseholdAccountsAccountIdRoute,
  }

const AuthedHouseholdAccountsRouteWithChildren =
  AuthedHouseholdAccountsRoute._addFileChildren(
    AuthedHouseholdAccountsRouteChildren,
  )

interface AuthedHouseholdExploreScenariosRouteChildren {
  AuthedHouseholdExploreScenariosIdRoute: typeof AuthedHouseholdExploreScenariosIdRoute
}

const AuthedHouseholdExploreScenariosRouteChildren: AuthedHouseholdExploreScenariosRouteChildren =
  {
    AuthedHouseholdExploreScenariosIdRoute:
      AuthedHouseholdExploreScenariosIdRoute,
  }

const AuthedHouseholdExploreScenariosRouteWithChildren =
  AuthedHouseholdExploreScenariosRoute._addFileChildren(
    AuthedHouseholdExploreScenariosRouteChildren,
  )

interface AuthedHouseholdExploreRouteChildren {
  AuthedHouseholdExploreAffordRoute: typeof AuthedHouseholdExploreAffordRoute
  AuthedHouseholdExploreScenariosRoute: typeof AuthedHouseholdExploreScenariosRouteWithChildren
  AuthedHouseholdExploreIndexRoute: typeof AuthedHouseholdExploreIndexRoute
}

const AuthedHouseholdExploreRouteChildren: AuthedHouseholdExploreRouteChildren =
  {
    AuthedHouseholdExploreAffordRoute: AuthedHouseholdExploreAffordRoute,
    AuthedHouseholdExploreScenariosRoute:
      AuthedHouseholdExploreScenariosRouteWithChildren,
    AuthedHouseholdExploreIndexRoute: AuthedHouseholdExploreIndexRoute,
  }

const AuthedHouseholdExploreRouteWithChildren =
  AuthedHouseholdExploreRoute._addFileChildren(
    AuthedHouseholdExploreRouteChildren,
  )

interface AuthedHouseholdGoalsRouteChildren {
  AuthedHouseholdGoalsGoalIdRoute: typeof AuthedHouseholdGoalsGoalIdRoute
}

const AuthedHouseholdGoalsRouteChildren: AuthedHouseholdGoalsRouteChildren = {
  AuthedHouseholdGoalsGoalIdRoute: AuthedHouseholdGoalsGoalIdRoute,
}

const AuthedHouseholdGoalsRouteWithChildren =
  AuthedHouseholdGoalsRoute._addFileChildren(AuthedHouseholdGoalsRouteChildren)

interface AuthedHouseholdHouseholdRouteChildren {
  AuthedHouseholdHouseholdChangelogRoute: typeof AuthedHouseholdHouseholdChangelogRoute
  AuthedHouseholdHouseholdLogsRoute: typeof AuthedHouseholdHouseholdLogsRoute
  AuthedHouseholdHouseholdIndexRoute: typeof AuthedHouseholdHouseholdIndexRoute
}

const AuthedHouseholdHouseholdRouteChildren: AuthedHouseholdHouseholdRouteChildren =
  {
    AuthedHouseholdHouseholdChangelogRoute:
      AuthedHouseholdHouseholdChangelogRoute,
    AuthedHouseholdHouseholdLogsRoute: AuthedHouseholdHouseholdLogsRoute,
    AuthedHouseholdHouseholdIndexRoute: AuthedHouseholdHouseholdIndexRoute,
  }

const AuthedHouseholdHouseholdRouteWithChildren =
  AuthedHouseholdHouseholdRoute._addFileChildren(
    AuthedHouseholdHouseholdRouteChildren,
  )

interface AuthedHouseholdInsightsRouteChildren {
  AuthedHouseholdInsightsPerksRoute: typeof AuthedHouseholdInsightsPerksRoute
  AuthedHouseholdInsightsIndexRoute: typeof AuthedHouseholdInsightsIndexRoute
}

const AuthedHouseholdInsightsRouteChildren: AuthedHouseholdInsightsRouteChildren =
  {
    AuthedHouseholdInsightsPerksRoute: AuthedHouseholdInsightsPerksRoute,
    AuthedHouseholdInsightsIndexRoute: AuthedHouseholdInsightsIndexRoute,
  }

const AuthedHouseholdInsightsRouteWithChildren =
  AuthedHouseholdInsightsRoute._addFileChildren(
    AuthedHouseholdInsightsRouteChildren,
  )

interface AuthedHouseholdReviewRulesRouteChildren {
  AuthedHouseholdReviewRulesRuleIdRoute: typeof AuthedHouseholdReviewRulesRuleIdRoute
}

const AuthedHouseholdReviewRulesRouteChildren: AuthedHouseholdReviewRulesRouteChildren =
  {
    AuthedHouseholdReviewRulesRuleIdRoute:
      AuthedHouseholdReviewRulesRuleIdRoute,
  }

const AuthedHouseholdReviewRulesRouteWithChildren =
  AuthedHouseholdReviewRulesRoute._addFileChildren(
    AuthedHouseholdReviewRulesRouteChildren,
  )

interface AuthedHouseholdReviewRouteChildren {
  AuthedHouseholdReviewRulesRoute: typeof AuthedHouseholdReviewRulesRouteWithChildren
  AuthedHouseholdReviewIndexRoute: typeof AuthedHouseholdReviewIndexRoute
}

const AuthedHouseholdReviewRouteChildren: AuthedHouseholdReviewRouteChildren = {
  AuthedHouseholdReviewRulesRoute: AuthedHouseholdReviewRulesRouteWithChildren,
  AuthedHouseholdReviewIndexRoute: AuthedHouseholdReviewIndexRoute,
}

const AuthedHouseholdReviewRouteWithChildren =
  AuthedHouseholdReviewRoute._addFileChildren(
    AuthedHouseholdReviewRouteChildren,
  )

interface AuthedHouseholdMonthMonthRouteChildren {
  AuthedHouseholdMonthMonthPlanRoute: typeof AuthedHouseholdMonthMonthPlanRoute
  AuthedHouseholdMonthMonthIndexRoute: typeof AuthedHouseholdMonthMonthIndexRoute
}

const AuthedHouseholdMonthMonthRouteChildren: AuthedHouseholdMonthMonthRouteChildren =
  {
    AuthedHouseholdMonthMonthPlanRoute: AuthedHouseholdMonthMonthPlanRoute,
    AuthedHouseholdMonthMonthIndexRoute: AuthedHouseholdMonthMonthIndexRoute,
  }

const AuthedHouseholdMonthMonthRouteWithChildren =
  AuthedHouseholdMonthMonthRoute._addFileChildren(
    AuthedHouseholdMonthMonthRouteChildren,
  )

interface AuthedHouseholdPlanMonthHomeRouteChildren {
  AuthedHouseholdPlanMonthHomeIndexRoute: typeof AuthedHouseholdPlanMonthHomeIndexRoute
  AuthedHouseholdPlanMonthHomeBucketsIdRoute: typeof AuthedHouseholdPlanMonthHomeBucketsIdRoute
  AuthedHouseholdPlanMonthHomeBucketsIndexRoute: typeof AuthedHouseholdPlanMonthHomeBucketsIndexRoute
}

const AuthedHouseholdPlanMonthHomeRouteChildren: AuthedHouseholdPlanMonthHomeRouteChildren =
  {
    AuthedHouseholdPlanMonthHomeIndexRoute:
      AuthedHouseholdPlanMonthHomeIndexRoute,
    AuthedHouseholdPlanMonthHomeBucketsIdRoute:
      AuthedHouseholdPlanMonthHomeBucketsIdRoute,
    AuthedHouseholdPlanMonthHomeBucketsIndexRoute:
      AuthedHouseholdPlanMonthHomeBucketsIndexRoute,
  }

const AuthedHouseholdPlanMonthHomeRouteWithChildren =
  AuthedHouseholdPlanMonthHomeRoute._addFileChildren(
    AuthedHouseholdPlanMonthHomeRouteChildren,
  )

interface AuthedHouseholdPlanMonthCommitmentsRouteChildren {
  AuthedHouseholdPlanMonthCommitmentsIdRoute: typeof AuthedHouseholdPlanMonthCommitmentsIdRoute
}

const AuthedHouseholdPlanMonthCommitmentsRouteChildren: AuthedHouseholdPlanMonthCommitmentsRouteChildren =
  {
    AuthedHouseholdPlanMonthCommitmentsIdRoute:
      AuthedHouseholdPlanMonthCommitmentsIdRoute,
  }

const AuthedHouseholdPlanMonthCommitmentsRouteWithChildren =
  AuthedHouseholdPlanMonthCommitmentsRoute._addFileChildren(
    AuthedHouseholdPlanMonthCommitmentsRouteChildren,
  )

interface AuthedHouseholdPlanMonthRouteChildren {
  AuthedHouseholdPlanMonthHomeRoute: typeof AuthedHouseholdPlanMonthHomeRouteWithChildren
  AuthedHouseholdPlanMonthCommitmentsRoute: typeof AuthedHouseholdPlanMonthCommitmentsRouteWithChildren
  AuthedHouseholdPlanMonthGoalsRoute: typeof AuthedHouseholdPlanMonthGoalsRoute
  AuthedHouseholdPlanMonthIncomeRoute: typeof AuthedHouseholdPlanMonthIncomeRoute
  AuthedHouseholdPlanMonthYearRoute: typeof AuthedHouseholdPlanMonthYearRoute
}

const AuthedHouseholdPlanMonthRouteChildren: AuthedHouseholdPlanMonthRouteChildren =
  {
    AuthedHouseholdPlanMonthHomeRoute:
      AuthedHouseholdPlanMonthHomeRouteWithChildren,
    AuthedHouseholdPlanMonthCommitmentsRoute:
      AuthedHouseholdPlanMonthCommitmentsRouteWithChildren,
    AuthedHouseholdPlanMonthGoalsRoute: AuthedHouseholdPlanMonthGoalsRoute,
    AuthedHouseholdPlanMonthIncomeRoute: AuthedHouseholdPlanMonthIncomeRoute,
    AuthedHouseholdPlanMonthYearRoute: AuthedHouseholdPlanMonthYearRoute,
  }

const AuthedHouseholdPlanMonthRouteWithChildren =
  AuthedHouseholdPlanMonthRoute._addFileChildren(
    AuthedHouseholdPlanMonthRouteChildren,
  )

interface AuthedHouseholdTransactionsMonthRouteChildren {
  AuthedHouseholdTransactionsMonthTransactionIdRoute: typeof AuthedHouseholdTransactionsMonthTransactionIdRoute
}

const AuthedHouseholdTransactionsMonthRouteChildren: AuthedHouseholdTransactionsMonthRouteChildren =
  {
    AuthedHouseholdTransactionsMonthTransactionIdRoute:
      AuthedHouseholdTransactionsMonthTransactionIdRoute,
  }

const AuthedHouseholdTransactionsMonthRouteWithChildren =
  AuthedHouseholdTransactionsMonthRoute._addFileChildren(
    AuthedHouseholdTransactionsMonthRouteChildren,
  )

interface AuthedHouseholdRouteChildren {
  AuthedHouseholdAccountsRoute: typeof AuthedHouseholdAccountsRouteWithChildren
  AuthedHouseholdAskRoute: typeof AuthedHouseholdAskRoute
  AuthedHouseholdCheckInRoute: typeof AuthedHouseholdCheckInRoute
  AuthedHouseholdExploreRoute: typeof AuthedHouseholdExploreRouteWithChildren
  AuthedHouseholdGlossaryRoute: typeof AuthedHouseholdGlossaryRoute
  AuthedHouseholdGoalsRoute: typeof AuthedHouseholdGoalsRouteWithChildren
  AuthedHouseholdHouseholdRoute: typeof AuthedHouseholdHouseholdRouteWithChildren
  AuthedHouseholdInsightsRoute: typeof AuthedHouseholdInsightsRouteWithChildren
  AuthedHouseholdPerksRoute: typeof AuthedHouseholdPerksRoute
  AuthedHouseholdReportsRoute: typeof AuthedHouseholdReportsRoute
  AuthedHouseholdReviewRoute: typeof AuthedHouseholdReviewRouteWithChildren
  AuthedHouseholdMonthMonthRoute: typeof AuthedHouseholdMonthMonthRouteWithChildren
  AuthedHouseholdPlanMonthRoute: typeof AuthedHouseholdPlanMonthRouteWithChildren
  AuthedHouseholdTransactionsMonthRoute: typeof AuthedHouseholdTransactionsMonthRouteWithChildren
  AuthedHouseholdMonthIndexRoute: typeof AuthedHouseholdMonthIndexRoute
  AuthedHouseholdPlanIndexRoute: typeof AuthedHouseholdPlanIndexRoute
  AuthedHouseholdTransactionsIndexRoute: typeof AuthedHouseholdTransactionsIndexRoute
  AuthedHouseholdGoalsAccountsAccountIdRoute: typeof AuthedHouseholdGoalsAccountsAccountIdRoute
  AuthedHouseholdPlanBucketsIdRoute: typeof AuthedHouseholdPlanBucketsIdRoute
  AuthedHouseholdPlanCommitmentsIdRoute: typeof AuthedHouseholdPlanCommitmentsIdRoute
  AuthedHouseholdPlanYearYearRoute: typeof AuthedHouseholdPlanYearYearRoute
}

const AuthedHouseholdRouteChildren: AuthedHouseholdRouteChildren = {
  AuthedHouseholdAccountsRoute: AuthedHouseholdAccountsRouteWithChildren,
  AuthedHouseholdAskRoute: AuthedHouseholdAskRoute,
  AuthedHouseholdCheckInRoute: AuthedHouseholdCheckInRoute,
  AuthedHouseholdExploreRoute: AuthedHouseholdExploreRouteWithChildren,
  AuthedHouseholdGlossaryRoute: AuthedHouseholdGlossaryRoute,
  AuthedHouseholdGoalsRoute: AuthedHouseholdGoalsRouteWithChildren,
  AuthedHouseholdHouseholdRoute: AuthedHouseholdHouseholdRouteWithChildren,
  AuthedHouseholdInsightsRoute: AuthedHouseholdInsightsRouteWithChildren,
  AuthedHouseholdPerksRoute: AuthedHouseholdPerksRoute,
  AuthedHouseholdReportsRoute: AuthedHouseholdReportsRoute,
  AuthedHouseholdReviewRoute: AuthedHouseholdReviewRouteWithChildren,
  AuthedHouseholdMonthMonthRoute: AuthedHouseholdMonthMonthRouteWithChildren,
  AuthedHouseholdPlanMonthRoute: AuthedHouseholdPlanMonthRouteWithChildren,
  AuthedHouseholdTransactionsMonthRoute:
    AuthedHouseholdTransactionsMonthRouteWithChildren,
  AuthedHouseholdMonthIndexRoute: AuthedHouseholdMonthIndexRoute,
  AuthedHouseholdPlanIndexRoute: AuthedHouseholdPlanIndexRoute,
  AuthedHouseholdTransactionsIndexRoute: AuthedHouseholdTransactionsIndexRoute,
  AuthedHouseholdGoalsAccountsAccountIdRoute:
    AuthedHouseholdGoalsAccountsAccountIdRoute,
  AuthedHouseholdPlanBucketsIdRoute: AuthedHouseholdPlanBucketsIdRoute,
  AuthedHouseholdPlanCommitmentsIdRoute: AuthedHouseholdPlanCommitmentsIdRoute,
  AuthedHouseholdPlanYearYearRoute: AuthedHouseholdPlanYearYearRoute,
}

const AuthedHouseholdRouteWithChildren = AuthedHouseholdRoute._addFileChildren(
  AuthedHouseholdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedHouseholdRoute: typeof AuthedHouseholdRouteWithChildren
  AuthedJoinedRoute: typeof AuthedJoinedRoute
  AuthedSetupRoute: typeof AuthedSetupRoute
  AuthedWelcomeRoute: typeof AuthedWelcomeRoute
  AuthedBankReturnRoute: typeof AuthedBankReturnRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHouseholdRoute: AuthedHouseholdRouteWithChildren,
  AuthedJoinedRoute: AuthedJoinedRoute,
  AuthedSetupRoute: AuthedSetupRoute,
  AuthedWelcomeRoute: AuthedWelcomeRoute,
  AuthedBankReturnRoute: AuthedBankReturnRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
