/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedHouseholdRouteImport } from './routes/_authed/_household'
import { Route as AuthedWelcomeRouteImport } from './routes/_authed/welcome'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthedHouseholdHouseholdRouteImport } from './routes/_authed/_household/household'
import { Route as AuthedHouseholdGoalsIndexRouteImport } from './routes/_authed/_household/goals.index'
import { Route as AuthedHouseholdGoalsGoalIdRouteImport } from './routes/_authed/_household/goals.$goalId'
import { Route as AuthedHouseholdMonthIndexRouteImport } from './routes/_authed/_household/month.index'
import { Route as AuthedHouseholdMonthMonthRouteImport } from './routes/_authed/_household/month.$month'
import { Route as AuthedHouseholdTransactionsIndexRouteImport } from './routes/_authed/_household/transactions.index'
import { Route as AuthedHouseholdTransactionsMonthRouteImport } from './routes/_authed/_household/transactions.$month'
import { Route as AuthedHouseholdGoalsAccountsAccountIdRouteImport } from './routes/_authed/_household/goals.accounts.$accountId'
import { Route as AuthedHouseholdMonthMonthIndexRouteImport } from './routes/_authed/_household/month.$month.index'
import { Route as AuthedHouseholdMonthMonthPlanRouteImport } from './routes/_authed/_household/month.$month.plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHouseholdRoute = AuthedHouseholdRouteImport.update({
  id: '/_household',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWelcomeRoute = AuthedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthedRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHouseholdHouseholdRoute =
  AuthedHouseholdHouseholdRouteImport.update({
    id: '/household',
    path: '/household',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdGoalsIndexRoute =
  AuthedHouseholdGoalsIndexRouteImport.update({
    id: '/goals/',
    path: '/goals/',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdGoalsGoalIdRoute =
  AuthedHouseholdGoalsGoalIdRouteImport.update({
    id: '/goals/$goalId',
    path: '/goals/$goalId',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdMonthIndexRoute =
  AuthedHouseholdMonthIndexRouteImport.update({
    id: '/month/',
    path: '/month/',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdMonthMonthRoute =
  AuthedHouseholdMonthMonthRouteImport.update({
    id: '/month/$month',
    path: '/month/$month',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdTransactionsIndexRoute =
  AuthedHouseholdTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdTransactionsMonthRoute =
  AuthedHouseholdTransactionsMonthRouteImport.update({
    id: '/transactions/$month',
    path: '/transactions/$month',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdGoalsAccountsAccountIdRoute =
  AuthedHouseholdGoalsAccountsAccountIdRouteImport.update({
    id: '/goals/accounts/$accountId',
    path: '/goals/accounts/$accountId',
    getParentRoute: () => AuthedHouseholdRoute,
  } as any)
const AuthedHouseholdMonthMonthIndexRoute =
  AuthedHouseholdMonthMonthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedHouseholdMonthMonthRoute,
  } as any)
const AuthedHouseholdMonthMonthPlanRoute =
  AuthedHouseholdMonthMonthPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AuthedHouseholdMonthMonthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/household': typeof AuthedHouseholdHouseholdRoute
  '/goals/$goalId': typeof AuthedHouseholdGoalsGoalIdRoute
  '/month/$month': typeof AuthedHouseholdMonthMonthRouteWithChildren
  '/transactions/$month': typeof AuthedHouseholdTransactionsMonthRoute
  '/goals/': typeof AuthedHouseholdGoalsIndexRoute
  '/month/': typeof AuthedHouseholdMonthIndexRoute
  '/transactions/': typeof AuthedHouseholdTransactionsIndexRoute
  '/goals/accounts/$accountId': typeof AuthedHouseholdGoalsAccountsAccountIdRoute
  '/month/$month/plan': typeof AuthedHouseholdMonthMonthPlanRoute
  '/month/$month/': typeof AuthedHouseholdMonthMonthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/household': typeof AuthedHouseholdHouseholdRoute
  '/goals/$goalId': typeof AuthedHouseholdGoalsGoalIdRoute
  '/transactions/$month': typeof AuthedHouseholdTransactionsMonthRoute
  '/goals': typeof AuthedHouseholdGoalsIndexRoute
  '/month': typeof AuthedHouseholdMonthIndexRoute
  '/transactions': typeof AuthedHouseholdTransactionsIndexRoute
  '/goals/accounts/$accountId': typeof AuthedHouseholdGoalsAccountsAccountIdRoute
  '/month/$month/plan': typeof AuthedHouseholdMonthMonthPlanRoute
  '/month/$month': typeof AuthedHouseholdMonthMonthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/_household': typeof AuthedHouseholdRouteWithChildren
  '/_authed/welcome': typeof AuthedWelcomeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/_authed/_household/household': typeof AuthedHouseholdHouseholdRoute
  '/_authed/_household/goals/$goalId': typeof AuthedHouseholdGoalsGoalIdRoute
  '/_authed/_household/month/$month': typeof AuthedHouseholdMonthMonthRouteWithChildren
  '/_authed/_household/transactions/$month': typeof AuthedHouseholdTransactionsMonthRoute
  '/_authed/_household/goals/': typeof AuthedHouseholdGoalsIndexRoute
  '/_authed/_household/month/': typeof AuthedHouseholdMonthIndexRoute
  '/_authed/_household/transactions/': typeof AuthedHouseholdTransactionsIndexRoute
  '/_authed/_household/goals/accounts/$accountId': typeof AuthedHouseholdGoalsAccountsAccountIdRoute
  '/_authed/_household/month/$month/plan': typeof AuthedHouseholdMonthMonthPlanRoute
  '/_authed/_household/month/$month/': typeof AuthedHouseholdMonthMonthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/sign-in/$'
    | '/household'
    | '/goals/$goalId'
    | '/month/$month'
    | '/transactions/$month'
    | '/goals/'
    | '/month/'
    | '/transactions/'
    | '/goals/accounts/$accountId'
    | '/month/$month/plan'
    | '/month/$month/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/sign-in/$'
    | '/household'
    | '/goals/$goalId'
    | '/transactions/$month'
    | '/goals'
    | '/month'
    | '/transactions'
    | '/goals/accounts/$accountId'
    | '/month/$month/plan'
    | '/month/$month'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/_household'
    | '/_authed/welcome'
    | '/sign-in/$'
    | '/_authed/_household/household'
    | '/_authed/_household/goals/$goalId'
    | '/_authed/_household/month/$month'
    | '/_authed/_household/transactions/$month'
    | '/_authed/_household/goals/'
    | '/_authed/_household/month/'
    | '/_authed/_household/transactions/'
    | '/_authed/_household/goals/accounts/$accountId'
    | '/_authed/_household/month/$month/plan'
    | '/_authed/_household/month/$month/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_household': {
      id: '/_authed/_household'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedHouseholdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/welcome': {
      id: '/_authed/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthedWelcomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_household/household': {
      id: '/_authed/_household/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AuthedHouseholdHouseholdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/goals/': {
      id: '/_authed/_household/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AuthedHouseholdGoalsIndexRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/goals/$goalId': {
      id: '/_authed/_household/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof AuthedHouseholdGoalsGoalIdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/month/': {
      id: '/_authed/_household/month/'
      path: '/month'
      fullPath: '/month/'
      preLoaderRoute: typeof AuthedHouseholdMonthIndexRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/month/$month': {
      id: '/_authed/_household/month/$month'
      path: '/month/$month'
      fullPath: '/month/$month'
      preLoaderRoute: typeof AuthedHouseholdMonthMonthRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/transactions/': {
      id: '/_authed/_household/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthedHouseholdTransactionsIndexRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/transactions/$month': {
      id: '/_authed/_household/transactions/$month'
      path: '/transactions/$month'
      fullPath: '/transactions/$month'
      preLoaderRoute: typeof AuthedHouseholdTransactionsMonthRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/goals/accounts/$accountId': {
      id: '/_authed/_household/goals/accounts/$accountId'
      path: '/goals/accounts/$accountId'
      fullPath: '/goals/accounts/$accountId'
      preLoaderRoute: typeof AuthedHouseholdGoalsAccountsAccountIdRouteImport
      parentRoute: typeof AuthedHouseholdRoute
    }
    '/_authed/_household/month/$month/': {
      id: '/_authed/_household/month/$month/'
      path: '/'
      fullPath: '/month/$month/'
      preLoaderRoute: typeof AuthedHouseholdMonthMonthIndexRouteImport
      parentRoute: typeof AuthedHouseholdMonthMonthRoute
    }
    '/_authed/_household/month/$month/plan': {
      id: '/_authed/_household/month/$month/plan'
      path: '/plan'
      fullPath: '/month/$month/plan'
      preLoaderRoute: typeof AuthedHouseholdMonthMonthPlanRouteImport
      parentRoute: typeof AuthedHouseholdMonthMonthRoute
    }
  }
}

interface AuthedHouseholdMonthMonthRouteChildren {
  AuthedHouseholdMonthMonthPlanRoute: typeof AuthedHouseholdMonthMonthPlanRoute
  AuthedHouseholdMonthMonthIndexRoute: typeof AuthedHouseholdMonthMonthIndexRoute
}

const AuthedHouseholdMonthMonthRouteChildren: AuthedHouseholdMonthMonthRouteChildren =
  {
    AuthedHouseholdMonthMonthPlanRoute: AuthedHouseholdMonthMonthPlanRoute,
    AuthedHouseholdMonthMonthIndexRoute: AuthedHouseholdMonthMonthIndexRoute,
  }

const AuthedHouseholdMonthMonthRouteWithChildren =
  AuthedHouseholdMonthMonthRoute._addFileChildren(
    AuthedHouseholdMonthMonthRouteChildren,
  )

interface AuthedHouseholdRouteChildren {
  AuthedHouseholdHouseholdRoute: typeof AuthedHouseholdHouseholdRoute
  AuthedHouseholdGoalsGoalIdRoute: typeof AuthedHouseholdGoalsGoalIdRoute
  AuthedHouseholdMonthMonthRoute: typeof AuthedHouseholdMonthMonthRouteWithChildren
  AuthedHouseholdTransactionsMonthRoute: typeof AuthedHouseholdTransactionsMonthRoute
  AuthedHouseholdGoalsIndexRoute: typeof AuthedHouseholdGoalsIndexRoute
  AuthedHouseholdMonthIndexRoute: typeof AuthedHouseholdMonthIndexRoute
  AuthedHouseholdTransactionsIndexRoute: typeof AuthedHouseholdTransactionsIndexRoute
  AuthedHouseholdGoalsAccountsAccountIdRoute: typeof AuthedHouseholdGoalsAccountsAccountIdRoute
}

const AuthedHouseholdRouteChildren: AuthedHouseholdRouteChildren = {
  AuthedHouseholdHouseholdRoute: AuthedHouseholdHouseholdRoute,
  AuthedHouseholdGoalsGoalIdRoute: AuthedHouseholdGoalsGoalIdRoute,
  AuthedHouseholdMonthMonthRoute: AuthedHouseholdMonthMonthRouteWithChildren,
  AuthedHouseholdTransactionsMonthRoute: AuthedHouseholdTransactionsMonthRoute,
  AuthedHouseholdGoalsIndexRoute: AuthedHouseholdGoalsIndexRoute,
  AuthedHouseholdMonthIndexRoute: AuthedHouseholdMonthIndexRoute,
  AuthedHouseholdTransactionsIndexRoute: AuthedHouseholdTransactionsIndexRoute,
  AuthedHouseholdGoalsAccountsAccountIdRoute:
    AuthedHouseholdGoalsAccountsAccountIdRoute,
}

const AuthedHouseholdRouteWithChildren = AuthedHouseholdRoute._addFileChildren(
  AuthedHouseholdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedHouseholdRoute: typeof AuthedHouseholdRouteWithChildren
  AuthedWelcomeRoute: typeof AuthedWelcomeRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHouseholdRoute: AuthedHouseholdRouteWithChildren,
  AuthedWelcomeRoute: AuthedWelcomeRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
